export const sectors = {
  manufacturing: {
    name: "제조업 중심",
    prefix: "mf",
    caseId: "RH-MF-001",
    description: "제조 현장의 수집·검수·데이터 버전과 FDE의 적용·재수집 흐름",
    mobile: [8, 17, 18],
    names: [
      "서비스 소개",
      "역할 선택·작업 공간",
      "작업 공간 개요",
      "현장 과제 목록",
      "현장 과제 등록",
      "과제 상세",
      "수집팀·현장 인력 배정",
      "모바일 RGB 수집",
      "검수·라벨링",
      "데이터셋 라이브러리",
      "데이터셋 상세·버전",
      "모델 목록·상세",
      "장비·호환성",
      "배포 준비",
      "모의 적용 상태 확인",
      "이벤트·재수집",
      "모바일 작업함",
      "경력·교육",
      "데이터 접근·이용 조건",
      "작업 공간 설정",
      "현장 탐색",
    ],
    nav: [
      ["개요", 3, "dashboard"],
      ["현장 탐색", 21, "explore"],
      ["현장 과제", 4, "assignment"],
      ["현장 인력", 7, "groups"],
      ["검수·라벨링", 9, "fact_check"],
      ["데이터셋", 10, "dataset"],
      ["모델", 12, "neurology"],
      ["장비", 13, "precision_manufacturing"],
      ["배포·관제", 14, "monitoring"],
      ["접근 승인", 19, "shield"],
      ["설정", 20, "settings"],
    ],
    flows: [
      ["요청·검수", [21, 5, 6, 7, 9, 10, 11]],
      ["현장 수집", [18, 17, 8, 9]],
      ["FDE 적용·재수집", [12, 13, 14, 15, 16]],
    ],
    roles: {
      manager: "운영팀",
      researcher: "요청 기업",
      operator: "수집 담당",
      reviewer: "검수 담당",
      fde: "현장 적용 FDE",
    },
    roleEntry: {
      manager: 3,
      researcher: 10,
      operator: 17,
      reviewer: 9,
      fde: 14,
    },
    taskPage: 6,
    newPage: 5,
    reviewPage: 9,
    datasetPage: 11,
    accessPage: 19,
    defaultTask: "소형 부품 외관 검사 RGB 이미지 수집",
  },
  "small-business": {
    name: "소상공인 중심",
    prefix: "sb",
    caseId: "RH-SB-001",
    description:
      "생활권 현장에서 청년의 교육·유급 수집·검수·수행 이력을 연결하는 흐름",
    mobile: [10, 11, 18],
    names: [
      "서비스 소개",
      "역할 선택·작업 공간",
      "작업 공간 개요",
      "현장 탐색",
      "현장 상세·수집 조건",
      "수집 과제 목록",
      "데이터 요청 등록",
      "과제 상세·유급 조건",
      "교육·현장 인력 배정",
      "모바일 교육·적격",
      "모바일 작업함",
      "모바일 작업 전 확인",
      "모바일 영상 수집",
      "모바일 보완·중단 보고",
      "영상 검수·구간 라벨",
      "데이터셋 라이브러리",
      "데이터셋 상세·버전",
      "수행·보상 이력",
      "데이터 접근·이용 승인",
      "작업 공간 설정",
    ],
    nav: [
      ["개요", 3, "dashboard"],
      ["현장 탐색", 4, "explore"],
      ["수집 과제", 6, "assignment"],
      ["교육·현장 인력", 9, "groups"],
      ["검수", 15, "fact_check"],
      ["데이터셋", 16, "dataset"],
      ["수행·보상", 18, "payments"],
      ["접근 승인", 19, "shield"],
      ["설정", 20, "settings"],
    ],
    flows: [
      ["요청 기업", [4, 5, 7, 8, 16, 17, 19]],
      ["청년 현장 전문인력", [10, 11, 12, 13, 14, 18]],
      ["운영·검수", [6, 9, 15, 16, 18]],
    ],
    roles: {
      coordinator: "운영팀",
      merchant: "현장 제공자",
      researcher: "요청 기업",
      operator: "청년 현장 전문인력",
      reviewer: "검수 담당",
    },
    roleEntry: {
      coordinator: 3,
      merchant: 5,
      researcher: 4,
      operator: 11,
      reviewer: 15,
    },
    taskPage: 8,
    newPage: 7,
    reviewPage: 15,
    datasetPage: 17,
    accessPage: 19,
    defaultScenario: "restaurant",
    scenarios: {
      restaurant: {
        caseId: "RH-SB-001",
        datasetId: "RH-DS-SB-001",
        title: "식당 테이블 정리·식기 분류",
        defaultTask: "성수 식당 A · 테이블 정리와 식기 분류 1인칭 영상",
        site: "성수 식당 A",
        siteCategory: "음식점",
        dataType: "1인칭 영상·작업 구간",
        scope: "고객이 없는 마감 시간에 빈 식기·컵·트레이를 종류별로 정리",
        purpose: "테이블 정리와 식기 분류 작업의 시작·끝·성공 여부를 이해하는 평가",
        conditions: "성인 참여자의 동의를 확인하고 손과 빈 식기만 촬영합니다.",
        safety: "고객·얼굴·뜨거운 음식·깨진 식기는 수집 대상에서 제외합니다.",
        objects: "빈 식기·컵·트레이",
        segment: "식기 종류별 분류",
        step1: "식기 회수",
        step2: "종류별 분류",
        step3: "트레이 정리",
        target: "테이블 정리·식기 분류 보조",
        image: "restaurant-tableware-sorting.png",
        alt: "마감 시간의 식당에서 빈 식기와 트레이를 분류하는 성인 작업자의 손",
      },
      mart: {
        caseId: "RH-SB-002",
        datasetId: "RH-DS-SB-002",
        title: "동네마트 냉장상품 선입선출 진열",
        defaultTask: "망원 동네마트 A · 냉장상품 선입선출 진열 1인칭 영상",
        site: "망원 동네마트 A",
        siteCategory: "동네마트",
        dataType: "1인칭 영상·텔레오퍼레이션 구간",
        scope: "비영업 시간에 모형 우유팩을 기존 상품 앞으로 이동하고 새 상품을 뒤에 진열",
        purpose: "냉장상품 운반·선입선출 진열 순서와 성공·실패 구간을 이해하는 평가",
        conditions: "성인 참여자의 동의를 확인하고 모형 상품과 냉장 진열대만 촬영합니다.",
        safety: "고객·얼굴·실제 유통기한·무거운 적재물·가동 중인 냉장설비 조작은 제외합니다.",
        objects: "모형 우유팩·운반 상자·냉장 진열대",
        segment: "기존 상품 앞으로 이동",
        step1: "상품 운반",
        step2: "기존 상품 확인",
        step3: "선입선출 진열",
        target: "냉장상품 운반·선입선출 진열 보조",
        image: "neighborhood-mart-fifo-stocking.png",
        alt: "동네마트 냉장고에 모형 우유팩을 선입선출 방식으로 진열하는 성인 작업자의 손",
      },
    },
    datasetExamples: [
      {
        title: "전통시장 공동 박스 운반",
        site: "전통시장 · 확장 예시",
        dataType: "주행·적재 장면 이미지",
        image: "traditional-market-box-transport.png",
        alt: "전통시장 통로에서 상자를 운반하는 소형 카트",
      },
      {
        title: "세탁소 의류 분류·개기",
        site: "동네 세탁소 · 확장 예시",
        dataType: "손동작 장면 이미지",
        image: "laundry-garment-sorting.png",
        alt: "세탁소에서 의류를 종류별 바구니에 분류하는 성인 작업자의 손",
      },
      {
        title: "고령 점주 로봇 사용 지원",
        site: "생활권 매장 · 확장 예시",
        dataType: "설치·교육 장면 이미지",
        image: "senior-merchant-robot-onboarding.png",
        alt: "청년 기술 담당자가 고령 점주의 서비스 로봇 사용을 돕는 장면",
      },
      {
        title: "서울 장인 미싱 기술 기록",
        site: "봉제 작업실 · 확장 예시",
        dataType: "숙련 손동작 장면 이미지",
        image: "artisan-sewing-skill-capture.png",
        alt: "안전 가드가 설치된 미싱 작업을 기록하는 장면",
      },
      {
        title: "소규모 숙박업소 침구 정리",
        site: "게스트하우스·소형 숙박업소 · 확장 예시",
        dataType: "침구 정리 작업 장면 이미지",
        image: "lodging-bed-making.png",
        alt: "소규모 숙박업소 객실에서 흰 침구를 정돈하는 성인 작업자의 손",
      },
    ],
    defaultTask: "성수 식당 A · 테이블 정리와 식기 분류 1인칭 영상",
  },
};

export function screenId(sector, number) {
  return `${sectors[sector].prefix}-${String(number).padStart(2, "0")}`;
}
export function route(sector, number) {
  if (
    !sectors[sector] ||
    !Number.isInteger(number) ||
    number < 1 ||
    number > sectors[sector].names.length
  )
    throw new Error("Unknown screen");
  return `./${screenId(sector, number)}.html`;
}
export function escapeHtml(value = "") {
  return String(value).replace(
    /[&<>"']/g,
    (char) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        char
      ],
  );
}
