import { gateNames } from '../shared/state.mjs';
import { route, escapeHtml as e } from '../shared/catalog.mjs';
import { referenceArt, scenePhoto } from './reference-art.mjs';

export function extendedContent(sector, number, h) {
  const {c,s,icon,badge,status,card,button,link,notice,field,rows,photo,caseTag,taskTitle,gates,journey,shortTitle,actions,roundIcon,meta,roles,participants,linked,scenarioText} = h;
  const mf = sector === 'manufacturing';
  const site = mf ? '한빛 정밀 현장' : scenarioText('site');
  const dataType = mf ? 'RGB 이미지' : scenarioText('dataType');
  const scope = mf ? '비가동 작업대의 소형 부품 촬영·기록' : scenarioText('scope');
  const flow = (items,cls='') => `<div class="rh-explainer-flow ${cls}">${items.map(([t,d,i],n)=>`<section>${roundIcon(i)}<h3>${n+1}. ${t}</h3><p>${d}</p></section>`).join('')}</div>`;
  const summary = () => `<div class="rh-case-summary">${photo(mf,'compact')}<div>${caseTag(c)}<h2>${shortTitle}</h2><p>${scope}</p><div class="rh-tags">${badge(dataType)}${badge('수집 진행')}</div></div></div>`;
  const miniSteps = () => flow([['조건 확인','허용 범위와 교육·보상 합의','assignment'],['데이터 수집',scope,'dataset'],['검수·제공','검수 후 목적별 별도 승인','fact_check']]);
  const stagePhotos = labels => `<div class="rh-stage-photos">${labels.map((t,i)=>`<section><h3><span>${i+1}</span>${t}</h3>${mf?(scenePhoto(sector,number,'compact',i)||photo(true,'compact')):photo(false,'compact')}<p>${t} 단계의 업무 흐름</p></section>`).join('')}</div>`;
  const purposeRows = () => `<div class="rh-purpose-rows">${[
    ['조회·평가','검수 후 별도 이용 신청','신청 가능','assignment'],['모델 학습','추가 이용 합의 필요','미승인','neurology'],['외부 공유','권리·재제공 조건 검토 필요','미승인','shield'],
  ].map(([t,d,b,i])=>`<div>${mf?roundIcon(i):''}<section><h3>${t}</h3><p>${d}</p></section>${badge(b)}</div>`).join('')}</div>`;
  const restrictions = () => `<div class="rh-grid three rh-scope-cards">${card('허용 업무',`<ul><li>${scope}</li><li>수집 기록과 라벨 초안 작성</li><li>합의한 공간 안에서만 수행</li></ul>`,'rh-allowed')}${card('제한·금지 업무',`<ul><li>${mf?'설비 가동·조작':scenarioText('safety')}</li><li>${mf?'전문가의 최종 품질 판정':'개인정보·실제 영업 데이터 기록'}</li><li>허용하지 않은 구역 출입</li></ul>`,'rh-restricted')}${card('추가 조건',`<p>특이사항은 촬영 전에 감독자와 범위를 다시 협의합니다. 불명확하면 작업을 중단합니다.</p>${link(sector,mf?7:12,'조건 확인 →',true)}`)}</div>`;
  const roleDescriptions = {
    manager:['운영팀','교육·배정·이용 승인을 조율합니다.','dashboard',['프로젝트 관리','진행 현황','조건 조율']],
    coordinator:['운영팀','교육·배정·이용 승인을 조율합니다.','dashboard',['교육 확인','현장 조율','이용 승인']],
    merchant:['현장 제공자','허용된 현장과 촬영 조건을 제공합니다.','explore',['촬영 범위','현장 허용','조건 합의']],
    researcher:['요청 기업','필요한 데이터와 활용 목적을 정의합니다.','assignment',['수집 요청','진행 확인','이용 신청']],
    operator:[mf?'수집 담당':'청년 현장 전문인력','교육 후 허용된 데이터를 수집합니다.','groups',['교육 확인','데이터 수집','수집 기록']],
    reviewer:['검수 담당','수집한 기록을 독립적으로 검수합니다.','fact_check',['품질 확인','보완 요청','검수 결정']],
    fde:['현장 적용 FDE','별도 전문 역량으로 현장 적용을 준비합니다.','precision_manufacturing',['모델 평가','장비 연동','적용 확인']],
  };
  switch (s.kind) {
    case 'home': return `${mf?`${card('',summary(),'rh-home-case')}<section class="rh-home-message"><h2>현장의 작은 부품이<br>더 큰 가능성이 됩니다.</h2><p>청년의 현장 수집과 전문가의 검수를 연결하고, 적용 결과가 다음 수집으로 이어지도록 돕습니다.</p>${actions(link(sector,2,'시작하기 →',true)+link(sector,21,'현장 둘러보기'))}</section>`:`<section class="rh-home-intro"><p>청년의 유급 데이터 수집과 소상공인 현장을 연결합니다.</p>${actions(link(sector,2,'시작하기 →',true)+link(sector,4,'현장 둘러보기'))}${flow([['요청 기업','필요 데이터 정의','assignment'],['소상공인','현장 제공','explore'],['청년 현장 전문인력','교육 후 수집','groups'],['운영팀','과정 조율','shield']],'rh-home-roles')}</section><div class="rh-home-photo">${photo(false)}</div>`}${card('데이터가 만들어지는 과정',flow(mf?[
      ['청년의 현장 수집','허용된 작업대에서 RGB 이미지를 수집합니다.','groups'],['데이터 검수','수집 담당과 분리하여 품질을 확인합니다.','fact_check'],['현장 적용 준비','전문 인력이 적용 방식을 검토합니다.','neurology'],['다시, 더 나은 수집','적용 결과를 다음 수집 요청에 연결합니다.','dataset'],
    ]:[['교육','현장에 맞는 방법을 배웁니다.','groups'],['유급 수집','합의한 조건으로 데이터를 수집합니다.','assignment'],['검수','수집 기록을 확인합니다.','fact_check'],['수행 이력','경험이 기록으로 남습니다.','payments']]),'rh-home-flow')}${roles()}${notice('현장 수집, 독립 검수, 이용 승인과 지급 확인은 각각 담당 역할을 나누어 관리합니다.')}`;
    case 'entry': return `<div class="rh-role-grid rh-five-roles">${Object.keys(c.roles).map(id=>{
      const [t,d,i,tags]=roleDescriptions[id];
      const artIndex = (mf?['manager','researcher','operator','reviewer','fde']:['coordinator','merchant','researcher','operator','reviewer']).indexOf(id);
      return `<button class="rh-card rh-role-card" data-action="set-role" data-role="${id}" aria-pressed="false"><div class="rh-role-art">${referenceArt(sector,number,artIndex,'illustration')||icon(i)}</div><strong>${t}</strong><p>${d}</p><div class="rh-role-tags">${tags.map(t=>badge(t)).join('')}</div><span class="rh-text-link">이 역할 선택 →</span></button>`;
    }).join('')}</div><div class="rh-enter-action"><p>선택한 역할: <strong data-role-label></strong></p>${button('선택한 역할로 시작 →','enter',true)}</div>${card('업무 흐름 살펴보기',`<div class="rh-entry-example"><div>${caseTag(c)}<h2>${shortTitle}</h2><p>${scope}</p>${notice('역할별 접근 범위와 승인 단계가 구분됩니다.')}</div>${mf?miniSteps():stagePhotos(['작업 준비','허용된 수집','기록 확인'])}</div>`)}`;
    case 'tasks': {
      if (!mf) {
        const rowsHtml = Object.entries(c.scenarios).map(([id,item])=>`<tr data-search-item data-scenario-card="${id}"><td>${item.caseId}<small>현장 과제</small></td><td><strong>${item.title}</strong></td><td>${item.site}</td><td>${item.dataType}</td><td>${badge('수집 가능','blue')}<small>수집·검수 흐름 연결</small></td><td><a class="rh-button" href="${route(sector,c.taskPage)}" data-scenario-link="${id}">상세 보기 →</a></td></tr>`).join('');
        return `<div class="rh-toolbar-row"><label class="rh-search">${icon('search')}<input type="search" data-search placeholder="과제명·현장·상태 검색" aria-label="과제 검색"></label>${link(sector,c.newPage,'+ 새 과제',true)}</div><div class="rh-tabs" role="tablist" aria-label="과제 상태 필터">${['전체','수집 가능','수집 중','검수 대기','승인'].map((t,i)=>button(t,'filter-tab',false,`aria-pressed="${i===0?'true':'false'}"`)).join('')}</div>${card('',`<div class="rh-table-wrap"><table><thead><tr><th>과제 ID</th><th>과제명</th><th>현장</th><th>수집 데이터</th><th>진행 상태</th><th>다음 행동</th></tr></thead><tbody>${rowsHtml}</tbody></table></div>`,'rh-task-table')}${card('두 과제는 같은 수집·검수 체계로 운영됩니다.',stagePhotos(['과제 확인하기','현장에서 촬영하기','제출하고 검수하기']))}`;
      }
      return `<div class="rh-toolbar-row"><label class="rh-search">${icon('search')}<input type="search" data-search placeholder="과제명·현장·상태 검색" aria-label="과제 검색"></label>${link(sector,c.newPage,'+ 새 과제',true)}</div><div class="rh-tabs" role="tablist" aria-label="과제 상태 필터">${['전체','대기','수집 중','검수 대기','승인'].map((t,i)=>button(t,'filter-tab',false,`aria-pressed="${i===0?'true':'false'}"`)).join('')}</div>${card('',`<div class="rh-table-wrap"><table><thead><tr><th>과제 ID</th><th>과제명</th><th>현장</th><th>수집 데이터</th><th>수집·검수 상태</th><th>다음 행동</th></tr></thead><tbody><tr><td>${c.caseId}<small>모의 과제</small></td><td><strong>${shortTitle}</strong></td><td>${site}</td><td>${dataType}</td><td>${badge(status('session'),'blue')}<small>${status('review')}</small></td><td>${link(sector,c.taskPage,'상세 보기 →')}</td></tr></tbody></table></div>`,'rh-task-table')}${card('',`${roundIcon('assignment')}<h2>한 개 과제를 따라가는 연결형 데모입니다.</h2><p>등록한 과제의 조건 확인부터 수집·검수까지 이어서 살펴보세요.</p>${link(sector,c.newPage,'+ 새 현장 과제 만들기',true)}`,'rh-task-empty')}`;
    }
    case 'detail': return `${mf?card('',`<div class="rh-detail-hero"><div>${caseTag(c)}<h2>한빛 정밀 작업대</h2><p>소형 부품의 외관을 촬영하고 라벨 초안을 남기는 과제입니다. 요청부터 재수집까지 한 번에 연결합니다.</p></div>${photo(true)}<aside>${icon('robot')}<h3>현장의 작은 과제가<br>더 나은 내일을 만듭니다.</h3><p>수집 담당과 현장 적용 FDE의 역할을 나누어 연결합니다.</p></aside></div>`):`<div class="rh-grid two rh-detail-media">${photo(false)}${card('작업 개요',`${rows([['작업명',shortTitle],['현장',site],['과제 코드',scenarioText('caseId')]])}<h3 class="rh-subsection">작업 내용</h3><p>${scope}</p>`)}</div>`}${mf?`<div class="rh-grid main-side">${card('진행 단계',journey(sector))}${card('다음 행동',link(sector,7,'조건 확인 →',true)+notice('과제 진행을 위한 사전 조건을 확인합니다.'))}</div><div class="rh-grid four rh-detail-facts">${card('요청 정보',meta([['과제',c.caseId],['데이터',dataType],['목적','외관 판별 평가']]))}${card('팀 구성',meta([['수집','청년 수집 담당'],['검수','독립 검수 담당'],['적용','별도 FDE']]))}${card('현장 정보',meta([['공간','비가동 작업대'],['환경','안전 작업 공간'],['범위','촬영·기록만']]))}${card('데이터 수집 요건',meta([['방식','RGB 촬영'],['라벨','정상·불량·판정 보류'],['제외','장비 조작']]))}</div>`:`${card('유급·업무 조건',rows([['준비 시간','사전 합의 · 조건 확인 필요'],['수집 시간','사전 합의 · 조건 확인 필요'],['보완 시간','사전 합의 · 조건 확인 필요'],['보상 조건','사전 합의 · 조건 확인 필요'],['감독','운영팀 · 감독·중단 방법 확인']]))}${restrictions()}`}${notice('현장 촬영 허용과 데이터 이용 승인은 서로 다른 단계에서 확인합니다.')}`;
    case 'site': return `<div class="rh-grid two rh-detail-media">${photo(false)}${card('현장 정보',rows([['현장명',site],['수집 과제',shortTitle],['공간 유형','안전 작업 공간'],['촬영 환경','고객 없는 비영업 환경'],['감독자','운영팀 · 사전 협의']]))}</div>${restrictions()}${card('수집 진행 절차',miniSteps())}`;
    case 'assignment': {
      const person = (t,d,i) => `<div class="rh-assigned-person"><span class="rh-assigned-art">${referenceArt(sector,number,['groups','fact_check','precision_manufacturing'].indexOf(i),'illustration')||icon(i)}</span><div><h3>${t}</h3><p>${d}</p><small>담당 역할</small></div></div>`;
      return `${!mf?card('',summary(),'rh-assignment-summary'):''}<div class="rh-grid rh-assignment-grid"><div class="rh-form-stack">${card(mf?'현장 수집팀 (로컬 팀)':'배정할 인력',`<p>교육·허용 조건 확인 후 역할별로 배정합니다.</p>${person(mf?'수집 담당자 · 청년':'청년 현장 전문인력','지정된 절차에 따른 '+dataType+' 수집','groups')}${person('독립 검수 담당자','수집 기록의 품질과 허용 범위를 확인','fact_check')}`)}${mf?card('현장 적용 FDE · 별도 배정',person('현장 적용 FDE · 전문 직무','모델 평가, 장치 연동, 현장 적용을 담당','precision_manufacturing')):card('현장 업무',`${photo(false,'compact')}<p class="rh-hint">${scenarioText('objects')} 작업 장면</p>`)}</div>${card('배정 전 필수 확인 5가지',`<p>모든 조건을 확인해야 수집을 시작할 수 있습니다.</p>${gates()}${button('조건 확인 후 수집 시작','start',true)}${button('배정 안내 확인','assignment')}${notice('교육·동의·안전·시간·보상 조건을 배정 전에 확인합니다.')}`,'rh-assignment-gates')}</div>${notice(mf?'청년 수집 담당과 현장 적용 FDE는 별도 역할입니다. 자동 승급이나 채용 보장이 아닙니다.':'현장 제공자는 촬영 범위를, 운영팀은 교육·감독·유급 조건을 확인합니다.')}`;
    }
    case 'library': {
      if (!mf) {
        const live = Object.entries(c.scenarios).map(([id,item])=>`<article class="rh-card rh-dataset-scenario" data-search-item data-scenario-card="${id}"><figure class="rh-photo"><img src="./assets/scenarios/${e(item.image)}" alt="${e(item.alt)}"><figcaption>현장 업무 이미지</figcaption></figure><div><div class="rh-title-line"><p class="rh-kicker">${e(item.datasetId)}</p>${badge('전체 흐름 연결','blue')}</div><h2>${e(item.title)}</h2><p>${e(item.scope)}</p>${meta([['현장',e(item.site)],['데이터',e(item.dataType)],['연결 범위','요청·수집·검수·데이터셋']])}<div class="rh-tags">${badge('현장별 기록')}${badge('검수 상태 연동')}</div>${actions(`<a class="rh-button rh-primary" href="${route(sector,c.datasetPage)}" data-scenario-link="${id}">상세 흐름 →</a>`)}</div></article>`).join('');
        const examples = c.datasetExamples.map(item=>`<article class="rh-card rh-dataset-example" data-search-item><figure class="rh-photo compact"><img src="./assets/scenarios/${e(item.image)}" alt="${e(item.alt)}"><figcaption>업종 확장 이미지</figcaption></figure><div class="rh-title-line"><h3>${e(item.title)}</h3>${badge('준비 중')}</div><p>${e(item.site)}</p><p>${e(item.dataType)}</p>${notice('현장 협의와 수집 기준 정립 후 순차적으로 연결됩니다.')}</article>`).join('');
        return `<div class="rh-toolbar-row"><label class="rh-search">${icon('search')}<input type="search" data-search aria-label="데이터셋 검색" placeholder="데이터셋명·설명·출처 검색"></label>${link(sector,c.newPage,'+ 수집 요청')}</div><section><div class="rh-title-line"><div><p class="rh-kicker">ACTIVE DATASETS</p><h2>수집 흐름이 연결된 대표 데이터셋</h2></div>${badge('2개')}</div><div class="rh-grid two rh-dataset-live-grid">${live}</div></section><section class="rh-example-section"><div class="rh-title-line"><div><p class="rh-kicker">UPCOMING DATASETS</p><h2>확장 예정 업종</h2></div>${badge(`${c.datasetExamples.length}개 · 준비 중`)}</div><div class="rh-grid two rh-dataset-example-grid">${examples}</div></section>${notice('AI 학습과 로봇 연동은 데이터 이용 동의와 별도 기술 검증 이후 진행합니다.')}`;
      }
      return `<div class="rh-toolbar-row"><label class="rh-search">${icon('search')}<input type="search" data-search aria-label="데이터셋 검색" placeholder="데이터셋명·설명·출처 검색"></label>${link(sector,c.newPage,'+ 수집 요청')}</div>${card('',`<article class="rh-library-feature" data-search-item>${photo(true)}<div>${caseTag(c)}<h2>RGB 외관 검사</h2><p>소형 부품의 RGB 이미지와 라벨 초안을 모은 데이터셋입니다.</p><div class="rh-library-stats">${meta([['버전','v1 준비'],['수집 기록',status('markCount')+'건'],['데이터 출처',site]])}</div><div class="rh-tags">${badge('검수 '+status('review'),'blue')}${badge('이용 '+status('access'))}</div>${actions(link(sector,c.datasetPage,'상세 보기 →',true))}</div></article>`)}${card('현장의 데이터가 더 나은 검사를 만듭니다.',flow([['현장에서 수집','출처·조건과 함께 기록','groups'],['검수·라벨링','독립 검수자의 품질 확인','fact_check'],['데이터셋 구성','검수와 버전 연결','dataset'],['이용 승인','목적별 별도 이용 합의','shield']]))}`;
    }
    case 'dataset': {
      const provenance = `<ol class="rh-provenance">${[['요청',mf?c.caseId:scenarioText('caseId'),'assignment'],['현장',site,'explore'],['수집',status('collector'),'groups'],['검수',status('review'),'fact_check']].map(([t,d,i])=>`<li>${roundIcon(i)}<strong>${t}</strong><span>${d}</span></li>`).join('')}</ol>`;
      const versions = flow([['초안','수집 기록 정리','assignment'],['검수',status('review'),'fact_check'],['승인 버전','이용 상태: '+status('access'),'shield']],'rh-version-flow');
      const callout = `<div class="rh-bottom-callout"><p>학습 또는 외부 공유는 별도 승인이 필요합니다.</p>${link(sector,c.accessPage,'이용 조건 확인·신청 →',true)}</div>`;
      if (!mf) return `${card('',`<div class="rh-sb-dataset-hero"><div>${photo(false)}<p class="rh-hint">대표 작업 장면</p></div><div><div class="rh-title-line"><p>데이터셋 ID</p>${badge(status('review'),'blue')}</div><h2>${scenarioText('datasetId')}</h2><h3>${scenarioText('title')} 데이터셋</h3><p>${site}에서 ${scope} 과정을 기록합니다.</p>${provenance}${card('승인 버전 이력',versions)}</div></div><div class="rh-grid three rh-sb-dataset-records">${card('작업 구간 기록',`<div data-marks class="rh-records"></div><p class="rh-hint">저장된 구간과 작업 판정을 표시합니다.</p>`)}${card('검수·이용 상태',rows([['수집 기록',status('markCount')+'건'],['검수 상태',status('review')],['이용 승인',status('access')],['지급 상태',status('payment')]])+notice('각 상태는 독립적으로 확인합니다.'))}${card('환경 기록',rows([['장소',site],['작업 대상',scenarioText('objects')],['촬영 방식',scenarioText('dataType')],['허용 범위',scenarioText('conditions')]]))}</div>`,'rh-dataset-board')}${card('현장 적용 준비',`${rows([['목표 작업',scenarioText('target')],['입력','검수된 작업 구간·환경 기록'],['전문 역할','FDE의 모델·장비 적합성 확인'],['현재 상태','적용 조건 검토']])}${notice('RFM 학습과 로봇 제어는 이용 범위 승인 및 별도 기술 검증이 필요합니다.')}`)}${callout}`;
      return `<div class="rh-grid rh-mf-dataset-top">${card('',summary(),'rh-dataset-summary')}${card('데이터 출처',provenance)}</div><div class="rh-grid two">${card('버전 이력',versions)}${card('이용 범위 및 승인 상태',purposeRows())}</div><div class="rh-grid two">${card('기본 정보',rows([['사례 번호',c.caseId],['데이터셋',shortTitle],['현장',site],['데이터 형태',dataType],['기록 수',status('markCount')+'건'],['검수',status('review')]]))}${card('데이터 예시',`<div class="rh-reference-samples">${[1,2,3,4,5,6].map(i=>scenePhoto(sector,number,'compact',i)).join('')}</div><p class="rh-hint">생성 이미지 · 실제 데이터 샘플이 아닙니다.</p>`)}</div>${callout}`;
    }
    case 'model': return `${card('모델 정보',`<div class="rh-grid two">${rows([['모델명','미선정'],['적용 현장',site],['데이터 출처',c.caseId]])}${rows([['입력 데이터','RGB 이미지'],['출력 항목','정상 · 불량 · 판정 보류'],['평가 상태','미실행']])}</div>`)}<div class="rh-grid two">${card('데이터 미리보기',`<div class="rh-reference-samples rh-model-samples">${['정상 예시','불량 예시','판정 보류 예시'].map((t,i)=>`<div>${scenePhoto(sector,number,'compact',i)}<p>${t}</p></div>`).join('')}</div><p class="rh-hint">생성된 설명용 이미지 · 모델 판별 결과가 아닙니다.</p>${link(sector,11,'데이터 출처 확인 →')}`)}${card('다음 단계',`<ol class="rh-numbered-list"><li><strong>평가 방식 선택</strong><p>현장에 적합한 모델 후보를 검토합니다.</p></li><li><strong>이용 범위·기준 합의</strong><p>평가 데이터와 성공 기준을 먼저 확인합니다.</p></li><li><strong>전문 담당자 배정</strong><p>현장 적용 FDE와 적용 조건을 확인합니다.</p></li><li><strong>모의 적용 준비</strong><p>실제 추론 없이 UI 흐름을 확인합니다.</p></li></ol>${link(sector,14,'배포 준비 →',true)}`)}</div>${card('관련 정보',participants())}${notice('RFM 학습·파인튜닝·실제 추론은 이 프런트엔드 데모의 구현 범위가 아닙니다.')}`;
    case 'hardware': return `<div class="rh-grid two rh-hardware-grid">${card('브라우저 모의 UI 선택',`<p>실제 장치 없이 브라우저에서 상태 흐름을 확인합니다.</p><div class="rh-browser-illustration"><div class="rh-window-dots">● ● ● <span>모의 환경</span></div><div class="rh-grid two">${photo(true)}<div>${rows([['입력','RGB 이미지 예시'],['제어','연결 안 됨'],['출력','브라우저 상태 기록']])}${badge('장치 조작 없음')}</div></div></div>${miniSteps()}${link(sector,14,'브라우저 모의 UI 시작하기 →',true)}`)}${card('실제 장치 미연결',`<p>확인한 장치 또는 명시한 모의 환경만 연결합니다.</p><div class="rh-device-diagram">${roundIcon('monitoring')}<span>연결 안 함<br><small>실제 장치 미연결</small></span>${roundIcon('precision_manufacturing')}</div>${rows([['입력 판별','실제 모델·추론 미연결'],['호환성','실제 검증 미수행'],['담당','현장 적용 FDE']])}${notice('장치·인터페이스·안전 조건은 전문기업과 별도로 확인해야 합니다.')}`)}</div>${notice('이 화면은 실제 장치를 연결하거나 제어하지 않습니다.')}`;
    case 'deployment': return `${linked()}<div class="rh-grid main-side rh-deploy-grid">${card('사전 점검 체크리스트',`<p>아래 항목을 확인하고 모의 실행을 진행하세요.</p><div class="rh-check-list rh-review-checks">${[['데이터 이용','이용 범위와 현재 승인 상태 확인'],['입력 형식','RGB 이미지 형식 확인'],['담당 FDE','별도 전문 역할 확인'],['중단 방법','이상 상황의 중단 절차 확인']].map(([t,d],i)=>`<label><input type="checkbox" data-field="deployCheck${i}"><span><strong>${t}</strong><small>${d}</small></span></label>`).join('')}</div>`)}${card('실행 요약',`${rows([['과제 번호',c.caseId],['과제명',shortTitle],['현장','모의 환경'],['데이터셋','RGB 이미지'],['모델','미연결'],['장비','브라우저 UI'],['수행 역할','<span data-role-label></span>'],['실행 상태',status('simulation')]])}${button('모의 실행','simulate',true,'id="btn-run-sim"')}${button('FDE 역할 선택','role')}${notice('실제 데이터를 읽지 않고 UI 상태만 변경합니다.')}`)}</div>`;
    case 'monitor': return `<div class="rh-grid two">${card('모의 실행 상태',`<div class="rh-simulation-status">${roundIcon('monitoring')}<div><h2>${status('simulation')}</h2><p>실제 모델·장치는 연결되어 있지 않습니다.</p></div></div>${notice('브라우저 상태 시연입니다. 실제 추론·장치 제어가 아닙니다.')}${actions(button('모의 실행','simulate',true)+button('모의 중단','stop'))}`)}${card('연결된 항목',`<div class="rh-connected-list">${[[11,'데이터셋','RGB 이미지 · '+c.caseId,'dataset'],[12,'모델','평가 방식 미선정','neurology'],[13,'장비','브라우저 모의 UI','monitoring']].map(([n,t,d,i])=>`<a href="./mf-${n}.html">${roundIcon(i)}<div><h3>${t}</h3><p>${d}</p></div>${icon('arrow')}</a>`).join('')}</div>`)}</div>${card('실행 이벤트 기록',`<div class="rh-record-head"><span>이벤트 유형</span><span>발생 시간</span></div><div data-events></div>${actions(link(sector,16,'이벤트·재수집 →'))}`,'rh-event-card')}${card('',`${caseTag(c)}<p>데이터 수집은 청년 수집 담당이, 현장 적용은 FDE가 담당하는 별도 역할입니다.</p>`)}`;
    case 'incident': return `<div class="rh-grid main-side rh-incident-grid">${card('이슈 정보',`<div class="rh-case-summary">${photo(true,'compact')}<div>${badge('예시 이슈')}<h2>반사로 부품 식별이 어려운 장면</h2><p>촬영 각도와 조명 조건을 다시 확인하는 상황 예시입니다.</p>${caseTag(c)}</div></div>`)}${card('연결 원본 데이터',rows([['케이스 ID',c.caseId],['과제',shortTitle],['현장',site],['수집 유형',dataType]])+link(sector,11,'데이터셋 출처 보기'))}${card('재수집 요청 작성',`${field('재수집 이유','recollectionReason','촬영 각도와 조명 조건을 다시 확인합니다.',{area:true})}<div class="rh-grid three rh-recollect-options">${['촬영 각도','조명 조건','라벨 기준'].map((x,i)=>`<label><input type="checkbox" data-field="recollectCheck${i}">${x}</label>`).join('')}</div>${button('재수집 요청 작성','recollect',true)}${notice('원래 기록을 유지하며 재수집 요청 초안만 작성합니다.')}`)}${card('이전 기록 · 유지됨',`<div data-events></div>${photo(true,'compact')}<p class="rh-hint">참고용 생성 이미지입니다.</p>`)}</div>${card('관련 인력',participants())}`;
    case 'access': return `<div class="rh-grid main-side rh-access-hero">${card('',summary())}${card('데이터 이용 목적',purposeRows())}</div><div class="rh-grid three rh-access-status">${[['검수 상태','review','fact_check','품질 확인과 사유 기록'],['이용 승인 상태','access','shield','조회·평가 목적별 별도 승인'],['지급 상태','payment','payments','보상 조건·지급 여부 별도 확인']].map(([t,v,i,d])=>card('',`${roundIcon(i)}<div><h3>${t}</h3>${badge(status(v),'blue')}<p>${d}</p></div>`)).join('')}</div>${mf?card('데이터 이용 승인 현황',`<div class="rh-table-wrap"><table><thead><tr><th>이용 구분</th><th>승인 상태</th><th>확인할 내용</th></tr></thead><tbody><tr><td>조회·평가</td><td>${status('access')}</td><td>검수 후 별도 신청·운영팀 승인</td></tr><tr><td>학습</td><td>미승인</td><td>수집 동의와 추가 이용 합의</td></tr><tr><td>외부 공유</td><td>미승인</td><td>권리·재제공 조건 검토</td></tr></tbody></table></div>`):''}<div class="rh-grid two">${card('이용 신청하기',`<p>검수 완료 데이터의 조회·평가 이용을 신청합니다.</p>${button('평가 목적 이용 신청','request-access',true)}`)}${card('승인 작업',`${actions(button('조회·평가 승인','grant-access')+button('승인 기록 내보내기','export-demo'))}${notice('학습과 외부 공유는 별도 동의와 권한 확인이 필요합니다.')}`)}</div>`;
    case 'settings': return `<div class="rh-grid main-side"><section class="rh-card rh-workspace-banner"><div><p>Workspace</p><h2>${c.name}</h2><p>작은 현장의 기록을 모아, 다음 수집과 활용으로 연결합니다.</p></div>${icon('robot')}</section>${card('내 역할',`<h3 data-role-label></h3><p>역할에 따라 수행 가능한 작업과 승인 권한이 달라집니다.</p>${button('역할 변경','role',true)}`)}</div><div class="rh-grid three rh-policy-cards">${[
      ['개인정보 안내','얼굴·연락처·민감 정보는 허용된 범위에서만 처리하세요.','shield'],['기기 저장','현재 기기에 저장된 진행 상태를 확인합니다.','dataset'],['초기화 전 확인','초기화하면 현재 작업 공간의 진행 기록을 지웁니다. 먼저 내용을 확인하세요.','settings'],
    ].map(([t,d,i])=>card('',`${roundIcon(i)}<div><h3>${t}</h3><p>${d}</p></div>`)).join('')}</div>${mf?`<div class="rh-grid two">${card('작업 공간 개요',rows([['사례 번호',c.caseId],['과제',shortTitle],['현장',site],['수집 데이터',dataType]]))}${card('역할 안내',rows(Object.keys(c.roles).map(id=>[c.roles[id],roleDescriptions[id][1]])))}</div>`:card('대표 현장 사례',summary()+miniSteps())}${card('기기 데이터 관리',`<p>선택한 영상과 진행 기록의 보관 정책을 확인하세요.</p>${actions(button('진행 기록 보기','workflow')+button('진행 기록 초기화','reset-confirm'))}${notice('초기화 전 필요한 기록을 먼저 확인하세요.')}`)}`;
    case 'compensation': {
      const mobileCompletion = !mf ? card('',`<div class="rh-completion-head">${roundIcon('payments')}<div><p>완료된 현장 업무</p><h2>${shortTitle}</h2><small>${site}</small></div></div><div class="rh-grid three rh-completion-status">${[['수집 기록',status('markCount')+'건'],['검수',status('review')],['지급',status('payment')]].map(([t,v])=>`<div><span>${t}</span><strong>${v}</strong></div>`).join('')}</div><p class="rh-hint">${scenarioText('datasetId')} 데이터셋에 수행 기록이 연결되었습니다.</p>`,'rh-mobile-completion') : '';
      return `${mobileCompletion}<div class="rh-grid four rh-compensation-metrics">${[['준비','15분','안내 확인과 촬영 준비','assignment'],['수집','60분','허용된 과제 수행','dataset'],['보완','15분','조건 협의 후 보완','fact_check'],['합계','90분','계획 시간','payments']].map(([t,v,d,i])=>card('',`${roundIcon(i)}<div><p>${t} · 계획</p><strong>${v}</strong><small>${d}</small></div>`)).join('')}</div>${card('수행 이력',`<div class="rh-table-wrap"><table><thead><tr><th>과제 ID</th><th>과제명</th><th>현장</th><th>수집 기록</th><th>검수 상태</th><th>보상 조건</th><th>지급 상태</th></tr></thead><tbody><tr><td>${mf?c.caseId:scenarioText('caseId')}</td><td>${shortTitle}</td><td>${site}</td><td>${status('markCount')}건</td><td>${status('review')}</td><td>사전 합의</td><td>${status('payment')}</td></tr></tbody></table></div>${!mf?actions(button('지급 확인','confirm-payment',true)):''}${notice('검수 승인과 지급 확인은 별도 단계로 관리됩니다.')}`)}<div class="rh-grid main-side">${card('수행 과정',stagePhotos(['준비','수집','보완']))}${card('기록된 핵심 역량',`<div class="rh-skill-list">${[['1인칭 촬영','촬영 조건과 범위 준수','dataset'],['구간 기록','시작·끝과 작업 내용 기록','assignment'],['조건 준수','허용 범위와 안전 조건 확인','shield']].map(([t,d,i])=>`<section>${roundIcon(i)}<div><h3>${t}</h3><p>${d}</p></div></section>`).join('')}</div>`)}</div>`;
    }
    case 'inbox': return `${card('',`<div class="rh-title-line">${badge(mf?c.caseId:scenarioText('caseId'),'blue')}${badge(status('session'))}</div><div class="rh-inbox-title"><div><h2>${shortTitle}</h2><p>${site}</p><p>청년 현장 전문인력</p></div>${mf?photo(true,'compact'):''}</div>${!mf?photo(false):''}<div class="rh-inbox-gates"><h3>작업 전 확인할 5가지 조건</h3><ul>${gateNames.map((g,i)=>`<li>${roundIcon(['assignment','explore','shield','fact_check','payments'][i])}<span>${i+1}. ${g}</span></li>`).join('')}</ul><p data-gate-status></p></div>${link(sector,mf?8:12,'작업 전 확인 →',true)}${actions(link(sector,mf?18:10,'교육 보기')+link(sector,18,mf?'작업 이력':'수행·보상 안내'))}${notice('현장에 도착하기 전 허용 범위와 안전·보상 조건을 확인하세요.')}`,'rh-inbox-card')}`;
    case 'preflight': return `<div class="rh-grid main-side rh-field-preflight">${card('',`<div class="rh-mobile-case"><div>${caseTag(c)}<h2>${shortTitle}</h2><div class="rh-tags">${badge('배정 완료')}${badge('고객 없는 공간')}</div></div>${photo(false,'compact')}</div>${rows([['현장',site],['수집 방식',dataType],['작업 대상',scenarioText('objects')]])}`)}${card('작업 전 확인',`<p data-gate-status></p><progress data-gate-progress max="5" value="0" aria-label="작업 전 조건 확인 진행"></progress>${gates()}${button('수집 시작','start',true)}${notice('다섯 조건을 모두 확인한 뒤 수집을 시작하세요.')}`)}</div>`;
    case 'training': return `<section class="rh-card rh-training-banner">${icon('robot')}<p>안전하고 정확한 데이터 수집을 위해<br>세 가지 안내를 먼저 확인해 주세요.</p></section><h2>짧은 교육 3가지</h2>${[
      ['안전한 현장 작업',scenarioText('safety')],['1인칭 촬영·구간 기록','손과 작업 물체가 보이는 장면에서 시작·끝·성공 여부를 기록합니다.'],['보상·보완 조건','준비·수집·보완 시간과 비용 부담자를 사전에 합의합니다.'],
    ].map(([t,d],i)=>card('',`<div class="rh-lesson-art">${scenePhoto(sector,number,'compact',i)||roundIcon('fact_check')}</div><div><h3><span>${i+1}</span>${t}</h3><p>${d}</p></div>`,'rh-lesson-card')).join('')}${card('',`${caseTag(c)}<h2>${shortTitle}</h2><p>과제 안내 예시이며 공인 교육이나 실제 이수 기록이 아닙니다.</p>`)}${link(sector,12,'작업 조건 확인 →',true)}`;
    case 'career': return `<section class="rh-card rh-training-banner"><div><h2>작은 기록이<br>현장의 변화를 만듭니다.</h2><p>지금의 경험이 다음 업무의 준비로 이어집니다.</p></div>${icon('robot')}</section><section class="rh-card rh-career-banner"><div><p>시작할 수 있는 업무</p><h2>데이터 수집</h2><p>허용된 대상물을 촬영하고 기록합니다.</p></div>${photo(true,'compact')}</section>${card('연결 과제',`${caseTag(c)}<h2>${shortTitle}</h2>${rows([['현장',site],['수집 방식',dataType],['수집 기록',status('markCount')+'건']])}`)}${card('준비할 기초 교육',`<div class="rh-grid two rh-career-options"><div>${roundIcon('shield')}<h3>현장 안전 기초</h3></div><div>${roundIcon('assignment')}<h3>RGB 촬영·기록</h3></div></div>`)}${card('선택할 수 있는 전문 경로',`<div class="rh-grid three rh-career-options">${[['품질 관리','fact_check'],['현장 기술지원','settings'],['현장 적용 FDE','groups']].map(([t,i])=>`<div>${roundIcon(i)}<h3>${t}</h3></div>`).join('')}</div>${notice('별도 역량·채용 요건이 필요합니다. 자동 승급이나 채용 보장이 아닙니다.')}`)}${link(sector,17,'작업함으로 돌아가기 →',true)}`;
    case 'rework': return `<div class="rh-grid main-side rh-field-rework">${card('',`${caseTag(c)}<h2>${shortTitle}</h2><div class="rh-rework-preview">${photo(false)}<div><h3>중단·보완 이유</h3><p data-value="reason"></p><p class="rh-hint">예시: ${scenarioText('objects')}가 가려진 구간은 촬영 조건을 다시 협의합니다.</p>${link(sector,13,'원본 수집 기록 보기 →')}</div></div>${notice('준비·보완 시간도 업무 조건에 포함합니다. 무급 재작업을 자동으로 요구하지 않습니다.')}`)}${card('상황 기록',`${field('이후 상황을 기록하세요','reworkNote','',{area:true})}${button('상황 기록 저장','save')}${actions(link(sector,12,'조건 다시 확인')+link(sector,11,'작업함',true))}`)}</div>`;
    case 'capture': {
      const conditionBlock = `<details class="rh-conditions"><summary>작업 조건 확인·세션 시작</summary>${gates()}${button('조건 확인 후 수집 시작','start',true)}<p class="rh-hint">다시 시작하면 현재 세션의 수집 기록이 초기화됩니다.</p></details>`;
      const context = card('',`<div class="rh-mobile-case"><div>${caseTag(c)}<h2>${shortTitle}</h2><p>${site} · ${dataType}</p></div>${roundIcon('assignment')}</div><div class="rh-inline-status">수집 ${badge(status('session'),'blue')}<span>기록 <strong data-value="markCount">0</strong>건</span></div>`);
      if (mf) return `${context}${card('',`<div class="rh-grid two rh-capture-preview"><div><h3>샘플 이미지</h3>${photo(true)}</div><div><h3>라벨 초안</h3><p>이미지를 확인하고 기록하세요.</p><div class="rh-choice">${['정상','불량','판정 보류'].map(x=>button(x,'label')).join('')}</div></div></div>`)}${card('촬영 조건',`${conditionBlock}${field('촬영 조건·특이사항','captureNotes','',{area:true})}`)}${actions(button('샘플 기록','capture',true)+button('작업 중단','stop'))}${card('수집 기록',`<div data-marks class="rh-records"></div>${button('검수 및 제출','submit',true)}`)}`;
      return `${context}<div class="rh-grid main-side rh-field-capture"><div class="rh-form-stack">${card('현장 영상',`${photo(false)}<video id="rh-video-preview" controls hidden playsinline aria-label="선택한 현장 영상 미리보기"></video><label class="rh-file-button">영상 선택<input id="rh-video-file" type="file" accept="video/*"></label><p id="rh-video-status" class="rh-hint">선택한 파일을 확인한 뒤 작업 구간을 기록하세요.</p>`)}${card('',`<div class="rh-title-line"><h2>작업 구간</h2>${button('+ 구간 추가','mark')}</div><div class="rh-segment-fields">${field('구간 이름','segmentName',c.scenarios[c.defaultScenario].segment,{scenarioField:'segment'})}${field('시작 (초)','segmentStart','0',{type:'number'})}${field('끝 (초)','segmentEnd','1',{type:'number'})}</div><details class="rh-saved-records"><summary>저장한 구간 확인 (<span data-value="markCount">0</span>건)</summary><div data-marks class="rh-records"></div></details>`)}</div><div class="rh-form-stack">${card('작업 판정',`<fieldset class="rh-choice rh-verdict"><legend class="rh-sr-only">작업 판정</legend>${[['success','성공'],['failure','실패'],['hold','판정 보류']].map(([v,t])=>`<label><input type="radio" name="verdict" value="${v}" ${v==='hold'?'checked':''}>${t}</label>`).join('')}</fieldset>`)}${card('환경·특이사항',field('촬영 조건과 특이사항','captureNotes','',{area:true}))}${conditionBlock}${actions(button('검수 및 제출','submit',true)+button('작업 중단','stop'))}</div></div>`;
    }
    default: return undefined;
  }
}
