import { sectors, screenId, route, escapeHtml as e } from '../shared/catalog.mjs';
import { gateNames } from '../shared/state.mjs';
import { specFor } from './screen-specs.mjs';
import { fidelityContent } from './fidelity.mjs';
import { scenePhoto } from './reference-art.mjs';

const paths = {
  robot: '<rect x="4" y="7" width="16" height="13" rx="4"/><path d="M12 3v4M1 12v4m22-4v4M8 16h8"/><path d="M8 11h.01M16 11h.01"/>',
  dashboard: '<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
  explore: '<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5Zm6-2v16m6-14v16"/>',
  assignment: '<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 3h6v4H9zM9 11h6m-6 5h6"/>',
  groups: '<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M17 5a3 3 0 0 1 0 6m1 4a5 5 0 0 1 3 5"/>',
  fact_check: '<path d="M9 5h11M9 12h11M9 19h11M2 5l1 1 3-3M2 12l1 1 3-3M2 19l1 1 3-3"/>',
  dataset: '<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5v14c0 4 18 4 18 0V5M3 12c0 4 18 4 18 0"/>',
  neurology: '<path d="m12 3 9 5v9l-9 5-9-5V8l9-5Zm0 10 9-5m-9 5L3 8m9 5v9"/>',
  precision_manufacturing: '<path d="M4 20h16M7 20v-5l5-4-3-6 4-2 5 9-5 5v3"/><circle cx="12" cy="12" r="2"/>',
  monitoring: '<rect x="3" y="3" width="18" height="14" rx="2"/><path d="M8 21h8m-4-4v4M6 11h3l2-4 3 7 2-3h2"/>',
  shield: '<path d="m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4Zm-4 9 3 3 5-6"/>',
  settings: '<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"/>',
  payments: '<rect x="2" y="5" width="20" height="15" rx="3"/><path d="M2 9h20m-7 5h3M5 2h13"/>',
  arrow: '<path d="M5 12h14m-6-6 6 6-6 6"/>',
  check: '<path d="m5 12 4 4 10-10"/>',
  plus: '<path d="M12 5v14M5 12h14"/>',
  menu: '<path d="M3 6h18M3 12h18M3 18h18"/>',
  search: '<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',
  back: '<path d="m14 5-7 7 7 7M7 12h14"/>',
};
export const icon = name => `<svg class="rh-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.assignment}</svg>`;
const badge = (text, tone = '') => `<span class="rh-badge ${tone}">${text}</span>`;
const status = field => `<span data-value="${field}">—</span>`;
const card = (title, content, cls = '') => `<section class="rh-card ${cls}">${title ? `<h2>${title}</h2>` : ''}${content}</section>`;
const button = (label, action, primary = false, attrs = '') => `<button type="button" data-action="${action}" class="${primary ? 'rh-primary' : ''}" ${attrs}>${label}</button>`;
const link = (sector, number, label, primary = false) => `<a class="rh-button ${primary ? 'rh-primary' : ''}" href="${route(sector, number)}">${label}</a>`;
const notice = text => `<p class="rh-note">${text}</p>`;
const field = (label, id, value = '', options = {}) => {
  const scenario = options.scenarioField ? ` data-scenario-field="${options.scenarioField}"` : '';
  return `<label class="rh-field" for="${id}">${label}${options.area ? `<textarea id="${id}" data-field="${id}"${scenario} rows="3">${e(value)}</textarea>` : `<input id="${id}" data-field="${id}"${scenario} type="${options.type || 'text'}" value="${e(value)}" ${options.type === 'number' ? 'min="1" max="100000"' : ''} ${options.required ? 'required' : ''}>`}</label>`;
};
const rows = entries => `<dl class="rh-details">${entries.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>`;
const photo = (mf, cls = '') => `<figure class="rh-photo ${cls}"><img src="./assets/${mf ? 'rgb-part' : 'tray-task'}.png" alt="${mf ? '안전한 작업대 위 금속 부품' : '1인칭 시점의 손이 빈 컵을 트레이에 정리하는 장면'}"><figcaption>${mf ? 'RGB 수집 이미지' : '현장 영상 장면'}</figcaption></figure>`;
const defaultScenario = c => c.scenarios?.[c.defaultScenario];
const scenarioText = (c, key) => {
  const value = defaultScenario(c)?.[key] ?? '';
  return `<span data-scenario-text="${key}">${e(value)}</span>`;
};
const scenarioImage = (c, cls = '') => {
  const scenario = defaultScenario(c);
  if (!scenario) return photo(true, cls);
  return `<figure class="rh-photo ${cls}"><img data-scenario-image src="./assets/scenarios/${e(scenario.image)}" alt="${e(scenario.alt)}"><figcaption>현장 이미지 · <span data-scenario-text="title">${e(scenario.title)}</span></figcaption></figure>`;
};
const caseTag = c => c.prefix === 'mf'
  ? `<p class="rh-kicker">${c.caseId} <span>· 한빛 정밀 모의 현장</span></p>`
  : `<p class="rh-kicker">${scenarioText(c,'caseId')} <span>· ${scenarioText(c,'site')}</span></p>`;
const taskTitle = c => `<span data-task-title>${e(c.defaultTask)}</span>`;
function gates() {
  const details = ['교육과 과제 수행 가능 여부를 확인합니다.', '허용 구역과 촬영 대상을 합의합니다.', '위험 요소와 감독·중단 방법을 확인합니다.', '준비·수집·보완 범위와 시간을 확인합니다.', '비용 부담자와 유급·보완 조건을 합의합니다.'];
  return `<div class="rh-gates">${gateNames.map((name,i)=>`<label><input type="checkbox" data-gate="${i}"><span><strong>${name}</strong><small>${details[i]}</small></span><span class="rh-sr-only" data-gate-badge="${i}">미확인</span></label>`).join('')}</div><p data-gate-status class="rh-hint" role="status"></p>`;
}
function journey(sector) {
  const mf = sector === 'manufacturing';
  const labels = mf ? ['요청','조건·배정','RGB 수집','검수','적용 확인','재수집'] : ['요청','조건 합의','교육·배정','수집','검수','데이터 제공'];
  const dest = mf ? [6,7,8,9,14,16] : [8,5,9,13,15,17];
  return `<ol class="rh-journey" aria-label="과제 진행 단계">${labels.map((s,i)=>`<li data-step="${i}"><a href="${route(sector,dest[i])}"><span>${i+1}</span>${s}</a></li>`).join('')}</ol>`;
}
function dataCards(sector) {
  return `<div class="rh-grid three rh-linked">${[
    ['데이터셋','RGB 이미지 · v1 준비',11,'dataset'],
    ['모델·평가','평가 방식 미선정',12,'neurology'],
    ['장비','브라우저 모의 UI',13,'precision_manufacturing'],
  ].map(([title,desc,n,i])=>`<a class="rh-card" href="${route(sector,n)}"><span class="rh-icon-tile">${icon(i)}</span><h3>${title}</h3><p>${desc}</p><span class="rh-text-link">기록 확인 ${icon('arrow')}</span></a>`).join('')}</div>`;
}
function roleCards(sector) {
  const mf=sector==='manufacturing';
  return `<div class="rh-grid three">${[
    ['요청 기업','필요한 데이터와 활용 목적 정의','assignment'],
    [mf?'제조 현장':'소상공인','허용된 작업 공간과 수집 조건 제공','explore'],
    ['청년 현장 전문인력','교육 후 유급 수집·기록 수행','groups'],
  ].map(([title,desc,i])=>card('',`<span class="rh-icon-tile">${icon(i)}</span><h3>${title}</h3><p>${desc}</p>`)).join('')}</div>`;
}
function metrics(items) {
  return `<div class="rh-grid ${items.length===4?'four':'three'} rh-metrics">${items.map(([label,value,desc])=>card('',`<span class="rh-muted">${label}</span><strong class="rh-metric">${value}</strong><small>${desc}</small>`)).join('')}</div>`;
}
function sceneMap(mf, c) {
  return `<div class="rh-map" role="img" aria-label="${mf?'지역 제조 현장':'생활권 수집 현장'} 운영 지도"><svg viewBox="0 0 540 540" aria-hidden="true"><rect width="540" height="540" fill="#EAF0F5"/><g fill="#D8E6D6"><path d="M0 0h165l-23 114L0 145z"/><path d="m390 320 150-22v242H396l-40-95z"/></g><g fill="#DBE3EB"><rect x="190" y="38" width="115" height="105" rx="12"/><rect x="55" y="189" width="110" height="99" rx="12"/><rect x="218" y="224" width="135" height="111" rx="12"/><rect x="43" y="377" width="156" height="110" rx="12"/><rect x="375" y="36" width="121" height="201" rx="12"/></g><g fill="none" stroke="#FFF" stroke-width="22"><path d="M-40 168 290 175l290 98M184-30l-8 269 94 330M-20 338l590 21"/></g><path d="M-40 450 200 513l270-130 100 9" fill="none" stroke="#B5D6EC" stroke-width="26"/><g fill="#2563EB" stroke="white" stroke-width="4"><circle cx="285" cy="271" r="20"/></g><text x="285" y="277" text-anchor="middle" fill="white" font-size="18">A</text><g fill="#94A3B8" stroke="white" stroke-width="3"><circle cx="112" cy="233" r="14"/><circle cx="408" cy="168" r="14"/></g></svg><span class="rh-map-disclaimer">${mf?'제조 권역':'생활권'} 보기</span><div class="rh-map-label">${mf?'한빛 정밀':scenarioText(c,'site')}<small>선택 현장 · 조건 협의 필요</small></div></div>`;
}

function pageContent(sector, number) {
  const c=sectors[sector], mf=sector==='manufacturing', s=specFor(sector,number);
  const refined = fidelityContent(sector, number, {c,s,icon,badge,status,card,button,link,notice,field,rows,photo:(isMF,cls='')=>isMF?(scenePhoto(sector,number,cls)||photo(true,cls)):scenarioImage(c,cls),caseTag,taskTitle,gates,journey,dataCards,roleCards,metrics,sceneMap:(isMF)=>sceneMap(isMF,c),scenarioText:(key)=>scenarioText(c,key)});
  if (refined !== undefined) return refined;
  const capture=mf?8:13, assignment=mf?7:9, inbox=mf?17:11, explorer=mf?21:4;
  const scope=mf?'비가동 작업대의 소형 부품 RGB 촬영·기록':'고객 없는 모의 공간에서 빈 비파손 컵을 트레이로 정리';
  const actionRow=html=>`<div class="rh-actions">${html}</div>`;
  switch(s.kind) {
    case 'home': return `<section class="rh-hero"><div>${badge('청년 Physical AI 현장 전문인력','blue')}<h2>${mf?'현장의 데이터가<br>새로운 기회가 되도록.':'우리 동네의 일이<br>AI의 배움이 되도록.'}</h2><p>${mf?'청년의 유급 수집과 전문기업의 적용·재수집을 연결합니다.':'현장은 소상공인이, 데이터 수집은 교육받은 청년이. 필요한 데이터를 함께 만듭니다.'}</p>${actionRow(link(sector,2,'데모 시작하기',true)+link(sector,explorer,'현장 둘러보기'))}<small>실제 채용·현장 계약·지급이 없는 프런트엔드 데모입니다.</small></div>${photo(mf)}</section>${roleCards(sector)}${card(mf?'수집부터 현장 개선까지':'교육부터 수행 이력까지',journey(sector)+notice(mf?'수집 담당과 FDE는 별도 직무입니다.':'검수 승인과 보상 지급 확인은 별도입니다.'))}`;
    case 'entry': return `<div class="rh-role-grid">${Object.entries(c.roles).map(([id,name])=>`<button class="rh-card rh-role-card" data-action="set-role" data-role="${id}" aria-pressed="false"><span class="rh-icon-tile">${icon(id==='fde'?'precision_manufacturing':'groups')}</span><strong>${name}</strong><p>${({manager:'교육·배정·이용 승인',coordinator:'교육·배정·이용 승인',researcher:'수집 요청과 데이터 이용 신청',merchant:'촬영 범위와 현장 조건 확인',operator:'교육 후 허용된 데이터 수집',reviewer:'수집 기록 검수와 보완 요청',fde:'별도 전문 역량으로 현장 적용'})[id]}</p><span class="rh-text-link">이 역할 선택</span></button>`).join('')}</div>${card('',`<p>선택한 역할: <strong data-role-label></strong></p>${actionRow(button('선택한 역할로 시작','enter',true))}${notice('역할 전환은 화면 테스트용이며 실제 로그인이나 서버 권한 부여가 아닙니다.')}`)}`;
    case 'overview': return `${metrics([['연결 과제','1','단일 과제 데모'],['검수 대기',status('pendingReview'),'이 브라우저의 진행 상태'],[mf?'이용 승인 대기':'보상 확인 대기',status(mf?'pendingAccess':'pendingPayment'),mf?'평가 목적 별도 승인':'검수와 지급은 별도']])}<div class="rh-grid main-side">${card('',`${caseTag(c)}<h2>${taskTitle(c)}</h2>${journey(sector)}<div class="rh-grid two"><div>${rows([['요청','AI 연구팀 · 예시'],['수집','로컬 수집팀 · 예시'],[mf?'현장 적용':'현장 제공',mf?'현장 적용 FDE':'모의 카페 A']])}<p class="rh-session-line">수집 ${status('session')} · 검수 ${status('review')}</p></div>${photo(mf,'compact')}</div>`)}${card('다음 할 일',`<ol class="rh-next-actions">${(mf?['촬영 조건 확인','수집 세션 검수','이용 승인 확인']:['작업 구간 검수','준비·보완 시간 확인','보상 조건 확인']).map((v,i)=>`<li><span>${i+1}</span>${v}</li>`).join('')}</ol>${link(sector,c.reviewPage,`검수 열기 ${icon('arrow')}`,true)}${notice(mf?'수집 담당과 FDE는 별도 직무입니다.':'검수 승인과 지급 확인은 별도입니다.')}<button class="rh-quiet" data-action="workflow">내 진행 기록 보기</button>`,'rh-next-card')}</div>${mf?dataCards(sector):roleCards(sector)}`;
    case 'tasks': return `${card('',`<div class="rh-toolbar-row"><label class="rh-search">${icon('search')}<input type="search" data-search placeholder="과제명·현장·상태 검색" aria-label="과제 검색"></label>${link(sector,c.newPage,`${icon('plus')} 새 과제`,true)}</div><div class="rh-tabs" role="tablist" aria-label="과제 상태 필터">${['전체','대기','수집 중','검수 대기','승인'].map((x,i)=>button(x,'filter-tab',false,`aria-pressed="${i===0?'true':'false'}"`)).join('')}</div><div class="rh-table-wrap"><table><thead><tr><th>과제</th><th>현장·데이터</th><th>수집</th><th>검수</th><th>다음 행동</th></tr></thead><tbody><tr><td><small>${c.caseId}</small><strong>${taskTitle(c)}</strong></td><td>${mf?'한빛 정밀 · RGB 이미지':'모의 카페 A · 1인칭 영상'}</td><td>${status('session')}</td><td>${status('review')}</td><td><a class="rh-text-link" href="${route(sector,c.taskPage)}">상세 보기 →</a></td></tr></tbody></table></div>`)}${notice('한 개 과제를 따라가는 연결형 데모입니다. 상태는 이 브라우저에서 수행한 작업으로 갱신됩니다.')}`;
    case 'request': return `<form class="rh-grid main-side">${card('수집 요청 내용',`<p class="rh-section-number">01 · 요청 목적</p>${field('과제명','taskName',c.defaultTask,{required:true})}${field('데이터 활용 목적','purpose',mf?'RGB 외관 판별 평가':'작업 영상의 구간 이해 평가',{area:true})}<p class="rh-section-number">02 · 수집 조건</p><div class="rh-grid two">${field(mf?'요청 이미지 수':'요청 세션 수',mf?'frameCount':'sessionCount','1',{type:'number',required:true})}${field('현장', 'siteName',mf?'한빛 정밀 모의 현장':'모의 카페 A')}</div>${field('촬영 범위·조건','captureConditions',scope,{area:true})}<p class="rh-section-number">03 · 교육·감독·보상</p>${field('비용 부담자와 유급·보완 조건','compensationTerms','사전 협의 필요',{area:true})}${actionRow(button('임시 저장','save')+button('과제 등록','create-task',true))}`)}${card('요청 요약',`${caseTag(c)}${rows([['수집 방식',mf?'RGB 이미지':'1인칭 작업 영상'],['작업 범위',scope],['다음 단계','다섯 가지 작업 조건 확인']])}${notice('요청 등록은 기존 데모 과제의 현재 상태를 새로 시작합니다. 실제 계약·배정이 아닙니다.')}`)}</form>`;
    case 'detail': return `${card('',`${caseTag(c)}<h2>${taskTitle(c)}</h2>${journey(sector)}<div class="rh-grid two">${photo(mf)}<div>${rows([['현장',mf?'한빛 정밀 모의 작업대':'모의 카페 A'],['수행 범위',scope],['교육·감독','운영팀과 사전 확인'],['준비·보완 시간','수행 범위에 포함하여 합의'],['보상','수집 전에 비용 부담자·조건 합의']])}${link(sector,assignment,'조건 확인',true)}</div></div>`)}<div class="rh-grid two">${card('허용된 업무',`<p>${scope}</p><p>수집 기록과 라벨 초안을 남깁니다.</p>`)}${card('제외하는 업무',`<p>${mf?'설비 가동·조작, 전문가의 최종 품질 판정':'고객·얼굴 촬영, 뜨거운 음료, 깨지는 컵 취급'}</p><p>불명확하면 작업을 중단하고 감독자에게 확인합니다.</p>`)}</div>`;
    case 'assignment': return `<div class="rh-grid two">${card('역할별 담당',`${caseTag(c)}<div class="rh-person"><span class="rh-avatar">A</span><div><h3>수집 담당 A · 예시</h3><p>교육 후 허용된 ${mf?'RGB 이미지':'1인칭 영상'} 수집</p></div></div><div class="rh-person"><span class="rh-avatar muted">B</span><div><h3>검수 담당 B · 예시</h3><p>수집 담당과 분리하여 기록 검수</p></div></div>${mf?notice('현장 적용 FDE는 별도 전문 직무입니다. 초급 수집 담당의 자동 승급 과정이 아닙니다.'):notice('현장 제공자는 촬영 범위를 확인하고, 운영팀은 감독·유급 조건을 조율합니다.')}${button('배정 화면 확인','assignment')}`)}${card('작업 전 다섯 가지 확인',`${gates()}${button('조건 확인 후 수집 시작','start',true)}${notice('체크는 UI 시연입니다. 실제 교육·동의·안전 확인을 대신하지 않습니다.')}`)}</div>`;
    case 'preflight': return `${card('',`${caseTag(c)}<h2>시작 전에 함께 확인해요</h2>${gates()}${button('수집 시작','start',true)}${notice('다섯 조건을 모두 확인해야 시작할 수 있습니다. 실제 허가나 교육 이수 기록은 아닙니다.')}`)}`;
    case 'capture': return `${card('',`${caseTag(c)}<div class="rh-inline-status">수집 ${badge(status('session'),'blue')}<span>기록 <strong data-value="markCount">0</strong>건</span></div><details class="rh-conditions"><summary>작업 조건 확인·세션 시작</summary>${gates()}${button('조건 확인 후 수집 시작','start',true)}<p class="rh-hint">다시 시작하면 현재 세션의 수집 기록이 초기화됩니다.</p></details>${photo(mf)}${mf?'':`<video id="rh-video-preview" controls hidden playsinline aria-label="선택한 로컬 영상 미리보기"></video><label class="rh-file-button">영상 선택 · 로컬 미리보기<input id="rh-video-file" type="file" accept="video/*"></label><p id="rh-video-status" class="rh-hint">파일은 서버로 전송하거나 저장하지 않습니다.</p>`}<h3>${mf?'라벨 초안':'작업 구간'}</h3>${mf?`<div class="rh-choice">${['정상','불량','판정 보류'].map(x=>button(x,'label')).join('')}</div>${field('촬영 조건·특이사항','captureNotes','',{area:true})}${button('샘플 기록','capture',true)}`:`<div class="rh-grid two">${field('시작 (초)','segmentStart','0',{type:'number'})}${field('끝 (초)','segmentEnd','1',{type:'number'})}</div>${field('작업 구간 이름','segmentName','컵 집기')}<fieldset class="rh-choice"><legend>성공 여부</legend>${[['success','성공'],['failure','실패'],['hold','판정 보류']].map(([v,t])=>`<label><input type="radio" name="verdict" value="${v}" ${v==='hold'?'checked':''}>${t}</label>`).join('')}</fieldset>${field('환경·특이사항','captureNotes','',{area:true})}${button('구간 추가','mark',true)}`}<div data-marks class="rh-records"></div>${actionRow(button('검수에 제출','submit',true)+button('작업 중단','stop'))}`)}`;
    case 'review': return `<div class="rh-review-layout">${card('수집 세션',`${caseTag(c)}<strong>S-001 · 모의 세션</strong><p>${status('review')}</p><p>기록 <strong data-value="markCount">0</strong>건</p>${rows([['수집 담당',status('collector')],['현재 역할','<span data-role-label></span>']])}${button('역할 변경','role')}`)}${card('',`${photo(mf)}<h2>${mf?'RGB 샘플 기록':'작업 구간 기록'}</h2><div data-marks class="rh-records"></div>${notice(mf?'생성 이미지는 샘플입니다. 실제 카메라 촬영이나 AI 품질 판정을 하지 않습니다.':'로컬 영상은 수집 페이지에서만 미리 볼 수 있습니다. 이 화면은 저장된 구간 메타데이터를 검수합니다.')}`)}${card('검수 기준',`<div class="rh-check-list">${(mf?['부품 식별','촬영 조건','라벨 초안','허용 범위']:['손·물체 식별','구간 라벨','개인정보 노출','촬영 조건']).map((t,i)=>`<label><input type="checkbox" data-field="reviewCheck${i}"><span>${t}</span></label>`).join('')}</div>${field('검수·보완 사유','rh-review-reason','',{area:true})}${actionRow(button('보완 요청','rework')+button('승인','approve',true))}${notice('검수 역할과 수집 역할을 분리합니다. 이용 승인·지급 상태는 별도로 유지됩니다.')}`)}</div>`;
    case 'library': return `${card('',`<label class="rh-search">${icon('search')}<input type="search" data-search placeholder="데이터셋·출처 검색" aria-label="데이터셋 검색"></label><article data-search-item class="rh-dataset-row">${photo(mf)}<div>${caseTag(c)}<h2>${mf?'RGB 외관 검사':'트레이 위 컵 정리'}</h2><p>${mf?'RGB 이미지·라벨 초안':'1인칭 영상·구간 메타데이터'}</p><div class="rh-tags">${badge('검수 '+status('review'))}${badge('이용 '+status('access'))}</div><p>v1 준비 · 수집 기록 <strong data-value="markCount">0</strong>건</p>${link(sector,c.datasetPage,'상세 보기',true)}</div></article>`)}${notice('데이터 판매 마켓이 아닌 출처·품질·이용 조건 관리 화면입니다.')}`;
    case 'dataset': return `${card('',`${caseTag(c)}<h2>${mf?'RGB 외관 검사':'트레이 위 컵 정리'} · v1</h2><div class="rh-grid two">${photo(mf,'compact')}<div>${rows([['데이터 형태',mf?'RGB 이미지·라벨 초안':'1인칭 영상·작업 구간·성공 여부'],['출처',mf?'한빛 정밀 모의 현장':'모의 카페 A'],['검수',status('review')],['이용 승인',status('access')]])}${link(sector,c.accessPage,'이용 조건 확인·신청',true)}</div></div>`)}${card('출처와 버전',`<ol class="rh-provenance"><li>요청<span>${c.caseId}</span></li><li>현장<span>${mf?'한빛 정밀':'모의 카페 A'}</span></li><li>수집<span data-value="markCount">0</span></li><li>검수<span data-value="review">미검수</span></li></ol><p>초안 → 검수 → 승인 버전 준비</p>${notice('평가 목적의 이용도 별도 승인이 필요합니다. 학습·외부 공유는 미승인 상태입니다.')}`)}`;
    case 'model': return `<div class="rh-grid main-side">${card('평가 방식 · 미선정',`${badge('평가 미실행')}<h3>RGB 외관 판별 평가</h3>${rows([['연결 데이터',`${c.caseId} · RGB 이미지`],['입력','허용된 RGB 이미지'],['출력','정상·불량·판정 보류'],['담당','현장 적용 FDE'],['실제 모델','미연결']])}${link(sector,11,'데이터 출처 확인')}`)}${card('적용 전에',`<ul class="rh-spaced-list"><li>데이터 이용 범위 확인</li><li>평가 방식·성공 기준 합의</li><li>숙련 기술 담당자 배정</li></ul>${link(sector,14,'배포 준비로 이동',true)}`)}</div>${notice('RFM 학습·파인튜닝·실제 추론은 이 프런트엔드 데모의 구현 범위가 아닙니다.')}`;
    case 'hardware': return `<div class="rh-grid two">${card('브라우저 모의 UI',`<span class="rh-icon-tile">${icon('monitoring')}</span>${badge('선택된 시연 환경','blue')}${rows([['입력','버튼으로 만든 모의 상태'],['출력','상태 표시·이벤트 기록'],['담당','현장 적용 FDE']])}${link(sector,14,'배포 준비',true)}`)}${card('실제 장치',`<span class="rh-icon-tile">${icon('precision_manufacturing')}</span>${badge('미연결')}<p>장치·인터페이스·현장 안전 조건을 전문기업과 별도로 확인해야 합니다.</p><p>실제 호환성 검증은 수행하지 않았습니다.</p>`)}</div>`;
    case 'deployment': return `${dataCards(sector)}<div class="rh-grid main-side">${card('모의 실행 전 확인',`<div class="rh-check-list">${['데이터 이용 상태 확인','입력 형식은 RGB 이미지','현장 적용 FDE 역할','모의 중단 방법 확인'].map((x,i)=>`<label><input type="checkbox" data-field="deployCheck${i}"><span>${x}</span></label>`).join('')}</div>${notice('이 체크리스트는 준비 내용 확인용입니다. 아래 버튼은 실제 데이터를 읽지 않고 UI 상태만 변경합니다.')}`)}${card('실행 요약',`${rows([['모드','브라우저 UI 시연'],['현재 역할','<span data-role-label></span>'],['실행 상태',status('simulation')]])}${button('모의 실행','simulate',true,'id="btn-run-sim"')}${button('FDE 역할 선택','role')}`)}</div>`;
    case 'monitor': return `${card('',`<p class="rh-kicker">BROWSER SIMULATION</p><h2>${status('simulation')}</h2><p>연결된 실제 모델·장치가 없습니다.</p>${actionRow(button('모의 실행','simulate',true)+button('모의 중단','stop')+link(sector,16,'이벤트·재수집'))}`)}${dataCards(sector)}${card('모의 실행 기록','<div data-events></div>')}`;
    case 'incident': return `<div class="rh-grid main-side">${card('보완할 데이터',`${caseTag(c)}${badge('예시 이슈')}<h3>반사로 부품 식별이 어려운 장면</h3>${field('재수집 이유','recollectionReason','촬영 각도와 조명 조건을 다시 확인합니다.',{area:true})}${rows([['확인할 조건','촬영 각도 · 조명 · 라벨 기준'],['원본 기록','현재 기록을 유지한 상태로 요청 초안 작성']])}${button('재수집 요청 작성','recollect',true)}`)}${card('연결된 기록',`<div data-events></div>${link(sector,11,'데이터셋 출처 보기')}`)}</div>`;
    case 'inbox': return `${card('',`${caseTag(c)}<h2>${taskTitle(c)}</h2>${photo(mf)}${badge('데이터 수집 오퍼레이터','blue')}<p data-gate-status></p>${rows([['수집 상태',status('session')],['검수',status('review')],['보상','사전 합의 필요']])}${link(sector,mf?8:12,'작업 전 조건 확인',true)}${actionRow(link(sector,mf?18:10,'교육 보기')+link(sector,mf?18:18,'수행 이력'))}`)}`;
    case 'training': return `${['안전한 컵 정리','1인칭 촬영·구간 기록','보상·보완 조건'].map((x,i)=>card('',`<p class="rh-section-number">0${i+1} · 기초 안내</p><h2>${x}</h2><p>${['빈 비파손 컵만 사용하고, 고객·뜨거운 음료를 촬영 대상에서 제외합니다.','손과 물체가 보이는 허용된 장면에서 작업의 시작·끝·성공 여부를 기록합니다.','준비·수집·보완 시간과 비용 부담자를 수집 전에 합의합니다.'][i]}</p>`)).join('')}${link(sector,12,'작업 조건 확인',true)}${notice('과제 안내 예시입니다. 실제 안전 교육 이수나 공인 자격 인증이 아닙니다.')}`;
    case 'career': return `${card('데이터 수집으로 시작',`<span class="rh-icon-tile">${icon('groups')}</span><h3>청년 Physical AI 현장 전문인력</h3><p>교육과 수행 기록을 모아 다음 업무를 준비합니다.</p>${rows([['기초 교육','현장 안전 · RGB 촬영·기록'],['연결 과제',c.caseId],['수집 기록',status('markCount')+'건']])}`)}${card('선택할 수 있는 전문 경로',`<ul class="rh-spaced-list"><li>데이터 품질 관리</li><li>현장 기술지원</li><li>현장 적용 FDE</li></ul>${notice('각 경로에는 별도 역량·채용 요건이 필요합니다. 교육 시간에 따른 자동 승급이나 채용 보장은 없습니다.')}`)}${link(sector,17,'작업함으로 돌아가기',true)}`;
    case 'rework': return `${card('보완·중단 사유',`${caseTag(c)}<p data-value="reason">아직 보완 요청이 없습니다.</p>${notice('예시: 컵이 가려진 구간은 촬영 조건을 다시 협의합니다.')}${field('상황 기록','reworkNote','',{area:true})}${button('상황 기록 저장','save')}`)}${card('다시 시작하기 전에',`<p>준비·보완 시간도 업무 조건에 포함해 확인합니다. 무급 재작업을 자동으로 요구하지 않습니다.</p>${link(sector,12,'조건 다시 확인',true)}${link(sector,11,'작업함')}`)}`;
    case 'compensation': return `${metrics([['준비 시간','15<small>분</small>','계획 예시'],['수집 시간','60<small>분</small>','계획 예시'],['보완 시간','15<small>분</small>','계획 예시'],['합계','90<small>분</small>','실측·정산 자료 아님']])}<div class="rh-grid main-side">${card('수행·지급 기록',`${caseTag(c)}<h3>${taskTitle(c)}</h3>${rows([['검수 상태',status('review')],['보상 조건','사전 합의 필요'],['지급 상태',status('payment')],['기록된 구간',status('markCount')+'건']])}${notice('금액 계산·실제 지급은 구현하지 않았습니다. 검수 승인이 지급 완료를 뜻하지 않습니다.')}`)}${card('기록할 수 있는 역량','<ul class="rh-spaced-list"><li>1인칭 촬영 조건 준수</li><li>작업 구간 기록</li><li>현장 허용 범위 확인</li></ul><p>수행 이력은 자격증이나 채용 보장이 아닙니다.</p>')}</div>`;
    case 'access': return `${metrics([['검수',status('review'),'품질 확인'],['평가 목적 이용',status('access'),'별도 이용 승인'],['지급',status('payment'),'보상 조건·지급 별도']])}${card('이용 목적별 범위',`<div class="rh-table-wrap"><table><thead><tr><th>목적</th><th>현재 상태</th><th>확인할 내용</th></tr></thead><tbody><tr><td>조회·평가</td><td>${status('access')}</td><td>검수 후 별도 신청·운영팀 승인</td></tr><tr><td>모델 학습</td><td>미승인</td><td>수집 동의와 별도 이용 합의 필요</td></tr><tr><td>외부 공유</td><td>미승인</td><td>권리·재제공 조건 검토 필요</td></tr></tbody></table></div>${actionRow(button('평가 목적 이용 신청','request-access')+button('운영팀 모의 승인','grant-access',true)+button('승인 기록 JSON','export-demo'))}${notice('실제 파일 접근 권한을 발급하지 않습니다. JSON에는 모의 메타데이터만 포함됩니다.')}`)}`;
    case 'settings': return `<div class="rh-grid two">${card('작업 공간·역할',`${rows([['제품',c.name],['현재 역할','<span data-role-label></span>'],['저장 위치','현재 브라우저의 로컬 저장 공간']])}${button('역할 변경','role',true)}`)}${card('데이터·진행 기록',`<p>두 제품의 상태는 별도 저장합니다. 실제 개인정보·민감 영상은 입력하지 마세요.</p><p>선택한 영상은 해당 페이지에서만 미리 보여주며 저장·전송하지 않습니다.</p>${button('진행 기록 보기','workflow')}${button('진행 기록 초기화','reset-confirm')}`)}</div>`;
    case 'site': return `<div class="rh-grid main-side">${card('',`${photo(false)}<h2>허용 업무 · 트레이 위 컵 정리</h2>${rows([['공간','고객 없는 모의 실습 공간'],['도구','빈 비파손 컵 · 트레이'],['촬영 방식','1인칭 영상'],['감독','운영팀과 사전 협의']])}`)}${card('수집 조건',`${badge('협의 필요')}<h3>현장 허용 범위를 먼저 확인하세요</h3><p>고객·얼굴·주소 등 개인정보를 포함하지 않습니다. 뜨거운 음료나 파손 위험이 있는 물체는 제외합니다.</p>${link(sector,7,'이 현장에 수집 요청',true)}`)}</div>`;
    case 'explorer': return `${card('',`<div class="rh-toolbar-row"><label class="rh-search">${icon('search')}<input type="search" data-search aria-label="현장 검색" placeholder="현장명·업무·데이터 검색"></label><label class="rh-toggle"><input type="checkbox" data-hide-map>지도 숨기기</label></div><div class="rh-map-layout">${sceneMap(mf)}<div class="rh-site-list"><article class="rh-card rh-selected-site" data-search-item>${photo(mf,'compact')}<div class="rh-title-line"><h2>${mf?'한빛 정밀 모의 현장':'모의 카페 A'}</h2>${badge('선택','blue')}</div><p>${mf?'소형 부품 외관 검사 · 비가동 작업대':'트레이 위 컵 정리 · 모의 실습 공간'}</p><div class="rh-tags">${(mf?['RGB 이미지','저위험 촬영','범위 협의 필요']:['1인칭 영상','빈 비파손 컵','고객 촬영 제외']).map(t=>badge(t)).join('')}</div>${actionRow(link(sector,mf?6:5,'현장 상세')+link(sector,c.newPage,'수집 요청',true))}</article>${(mf?['모의 금속가공 현장 B','모의 조립 현장 C']:['모의 베이커리 B','모의 서점 C']).map(n=>`<article class="rh-site-placeholder" data-search-item><span class="rh-icon-tile">${icon('explore')}</span><div><h3>${n}</h3><p>협의 전 · 수집 조건 미정</p></div></article>`).join('')}</div></div>`)}${notice('현장과 지도는 가상 예시이며 실제 사업장 위치·모집 현황·협약을 나타내지 않습니다.')}`;
    default: throw new Error(`No renderer: ${s.kind}`);
  }
}

export function renderPage(sector, number, { naverMapClientId = '' } = {}) {
  const c=sectors[sector], s=specFor(sector,number), mobile=c.mobile.includes(number), id=screenId(sector,number);
  const fieldWorkspace = sector === 'small-business' && [12,13,14].includes(number);
  const active= n => n===number || ({tasks:[c.newPage,c.taskPage],assignment:[sector==='manufacturing'?8:10],library:[c.datasetPage],deployment:[15,16]})[specFor(sector,n).kind]?.includes(number);
  const brand=`<a class="rh-brand" href="./index.html">${icon('robot')}<span>RoboHood</span></a>`;
  const sidebar=`<aside class="rh-sidebar" id="rh-sidebar">${brand}<nav aria-label="주 메뉴">${c.nav.map(([title,n,i])=>`<a href="${route(sector,n)}" ${active(n)?'aria-current="page"':''}>${icon(i)}${title}</a>`).join('')}</nav><div class="rh-sidebar-footer">${sector==='manufacturing'?photo(true,'rh-sidebar-photo'):''}<p>${sector==='manufacturing'?'작은 데이터가<br>큰 변화를 만듭니다.':'사람의 현장이<br>더 나은 일상을 만듭니다.'}</p><small>RoboHood</small><div class="rh-sidebar-tools"><a href="${route(sector,sector==='manufacturing'?17:11)}">현장 앱 열기</a></div></div></aside>`;
  const surfaceLabel = mobile ? '현장 앱' : fieldWorkspace ? '현장 작업' : '운영 콘솔';
  const header=`<header class="rh-header">${mobile?`<a class="rh-icon-button" href="${route(sector,sector==='manufacturing'?17:11)}" aria-label="작업함으로">${icon('back')}</a><strong>${icon('robot')}RoboHood</strong>`:`<button class="rh-menu rh-icon-button" data-action="menu" aria-label="메뉴 열기" aria-controls="rh-sidebar" aria-expanded="false">${icon('menu')}</button><span class="rh-product-label">${sector==='manufacturing'?'제조 현장 데이터 플랫폼':'소상공인 현장 데이터 플랫폼'}</span>`}${badge(surfaceLabel)}<div class="rh-header-actions">${mobile?'':`<button data-action="role" class="rh-quiet"><span class="rh-avatar tiny">${icon('groups')}</span><span data-role-label>운영팀</span><span aria-hidden="true">⌄</span></button>`}</div></header>`;
  const bottom=mobile?`<nav class="rh-bottom-nav" aria-label="현장 메뉴">${(sector==='manufacturing'?[[17,'작업함','assignment'],[8,'수집','dataset'],[18,'교육·이력','groups'],[3,'개요','dashboard']]:[[11,'작업함','assignment'],[13,'수집','dataset'],[10,'교육','groups'],[18,'이력','payments']]).map(([n,t,i])=>`<a href="${route(sector,n)}" ${n===number?'aria-current="page"':''}>${icon(i)}<span>${t}</span></a>`).join('')}</nav>`:'';
  const mapEnabled = sector === 'small-business' && number === 4 && Boolean(naverMapClientId);
  const config={...c,sector,number,id,isMobile:mobile,refined:true,...(mapEnabled?{naverMapClientId}:{})};
  const csp = mapEnabled
    ? "default-src 'self'; script-src 'self' https://oapi.map.naver.com https://openapi.map.naver.com https://*.pstatic.net http://oapi.map.naver.com http://nrbe.map.naver.net http://nrb.map.naver.net; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src 'self' data: blob: https://*.pstatic.net https://*.naver.net http://static.naver.net http://*.pstatic.net http://*.naver.net; media-src 'self' blob:; connect-src https://oapi.map.naver.com https://*.naver.com https://*.naver.net https://*.pstatic.net https://kr-col-ext.nelo.navercorp.com http://oapi.map.naver.com http://*.naver.net http://*.pstatic.net; worker-src blob:; object-src 'none'; base-uri 'none'; form-action 'none'"
    : "default-src 'self'; script-src 'self'; style-src 'self'; font-src 'self' data:; img-src 'self' data: blob:; media-src 'self' blob:; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'";
  const pageClass = `rh-kind-${s.kind} rh-sector-${c.prefix}`;
  const eyebrow = mobile ? '청년 현장 앱' : fieldWorkspace ? '청년 현장 작업' : `${c.name} 운영 콘솔`;
  const footer = mobile
    ? 'RoboHood 현장 앱 · 허용된 범위와 안전 조건을 확인하세요.'
    : fieldWorkspace
      ? 'RoboHood 현장 작업 · 작업 조건과 수집 기록을 한 화면에서 관리합니다.'
      : 'RoboHood 운영 콘솔 · 검수와 이용 권한을 역할별로 관리합니다.';
  const surface = mobile ? 'field-app' : fieldWorkspace ? 'field-workspace' : 'operations-console';
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="${csp}"><title>${s.title} · RoboHood</title><link rel="stylesheet" href="./assets/pretendard.css"><link rel="stylesheet" href="./assets/app.css"></head><body class="${mobile?'rh-mobile':'rh-desktop'} ${pageClass}" data-screen="${id}" data-surface="${surface}"><a class="rh-skip" href="#rh-main">본문으로 건너뛰기</a><div class="rh-app">${mobile?'':sidebar}${header}<main id="rh-main" class="rh-main"><div class="rh-page-heading"><div><p class="rh-eyebrow">${eyebrow}</p><h1>${s.title}</h1><p>${s.subtitle}</p></div>${number===3?(sector==='manufacturing'?link(sector,c.newPage,`${icon('plus')} 새 과제`,true):'<p class="rh-demo-notice">ⓘ 과제 진행 상태가 단계별로 갱신됩니다.</p>'):''}</div><div class="rh-page-content">${pageContent(sector,number)}</div><footer class="rh-page-footer"><span>${footer}</span></footer></main>${bottom}</div><dialog id="rh-dialog"><div class="rh-dialog-heading"><h2 id="rh-dialog-title"></h2>${button('닫기','close-dialog')}</div><div id="rh-dialog-body"></div></dialog><div id="rh-toast" role="status" hidden></div><script type="application/json" id="rh-config">${JSON.stringify(config).replaceAll('<','\\u003c')}</script><script type="module" src="./assets/app.mjs"></script></body></html>`;
}
