// v1 refined: one specification per generated image and implemented page.
// These are product requirements, not instructions extracted from exported HTML.
export const specifications = {
  manufacturing: [
    ['현장의 데이터, 청년의 다음 기회', '교육받은 청년의 유급 수집과 전문기업의 현장 적용을 연결합니다.', 'home', 'Public introduction. Hero explains youth paid RGB collection, quality review, specialist application and recollection. Three participant cards: 제조 현장 / AI 연구팀 / 청년 현장 전문인력. One safe small metal part tabletop photo. Buttons 데모 시작 and 현장 둘러보기. No employment statistics.'],
    ['어떤 역할로 둘러볼까요?', '실제 로그인 없이 역할별 데모 화면을 확인합니다.', 'entry', 'Five large role cards: 운영팀, 요청 기업, 수집 담당, 검수 담당, 현장 적용 FDE. Clearly separate collection and advanced engineering. Primary button 선택한 역할로 시작. No email/password, no certifications.'],
    ['현장의 다음 단계를 확인하세요', '수집한 데이터가 현장 개선으로 이어지는 과정', 'overview', 'Three compact metrics and six-step linked workflow 요청 / 조건·배정 / RGB 수집 / 검수 / 적용 확인 / 재수집. Main RH-MF-001 case card, next action panel, linked dataset/model/device summary. No unrelated tasks.'],
    ['현장 과제', '요청 목적과 담당자, 다음 행동을 확인하세요.', 'tasks', 'Search and one readable task table: RH-MF-001 소형 부품 외관 검사 / 한빛 정밀 / RGB 이미지 / 수집 조건 확인 / 상세 보기. New task button. Simple status tabs with proper empty state, not invented second case.'],
    ['새 수집 과제', '필요한 데이터와 현장 조건을 먼저 정의합니다.', 'request', 'Readable 800px form with 3 sections: 요청자·활용 목적 / 현장·RGB 수집 조건 / 교육·감독·보상. Fields 과제명, 평가 목적, 요청 수량, 촬영 조건. Right summary card RH-MF-001. Primary 과제 등록, secondary 임시 저장. No hardware specifications or subsidies.'],
    ['소형 부품 외관 검사', '하나의 과제로 요청부터 재수집까지 연결합니다.', 'detail', 'Case RH-MF-001, 한빛 정밀 모의 작업대. Six-step status journey, request/team/site cards, low-risk RGB capture and label draft requirements. Safe work scope excludes operating machinery. Next action 조건 확인.'],
    ['수집팀·현장 인력 배정', '직무와 교육·감독·보상 조건에 맞춰 배정합니다.', 'assignment', 'Two columns: local collection team card with roles 수집 담당 A and 검수 담당 B; right five-condition checklist. Separate slim FDE specialist card, not collector promotion. One clear assignment button. No certification levels or guaranteed rates.'],
    ['RGB 이미지 수집', '안전한 모의 작업대에서 촬영·라벨 초안을 기록합니다.', 'capture', 'Mobile single screen. Compact five-condition accordion, sample metal part image marked 생성 이미지, labels 정상 / 불량 / 판정 보류, button 샘플 기록, notes field 촬영 조건, 검수 제출 and 작업 중단. No real camera claim.'],
    ['RGB 이미지 검수', '촬영 품질과 라벨 초안을 확인하고 사유를 남깁니다.', 'review', 'Three columns: session list, large sample metal part image with label choices, review panel. Criteria 부품 식별 / 촬영 조건 / 라벨 / 허용 범위. Reason textarea, 보완 요청 and 승인. Collector and reviewer distinct. No AI scores.'],
    ['데이터셋 라이브러리', '출처와 검수 상태가 연결된 데이터 묶음입니다.', 'library', 'Searchable dataset card RGB 외관 검사 · RH-MF-001, version v1 준비, item count 미집계, source 한빛 정밀 모의 현장, separate review and access badges, 상세 보기. No marketplace sales.'],
    ['데이터셋 상세·버전', '수집 세션과 이용 조건, 변경 이력을 함께 확인합니다.', 'dataset', 'Dataset header RGB 외관 검사, provenance row 요청 / 현장 / 수집 / 검수, version timeline 초안→검수→승인 버전. Access scope 평가만 별도 승인, 학습·공유 미승인. Button 이용 신청.'],
    ['모델·평가 기록', '숙련 기술 담당자의 적용 방식을 연결합니다.', 'model', 'One model record 미선정, input RGB 이미지, output 정상·불량·판정 보류, data source RH-MF-001, evaluation 미실행. Right next steps checklist. No accuracy, model vendor, RFM training or GPU metrics.'],
    ['장비·호환성', '확인한 장치 또는 명시한 모의 환경만 연결합니다.', 'hardware', 'Two cards: 브라우저 모의 UI 선택 and 실제 장치 미연결. Input 판별 결과, output 상태 표시, responsible FDE. No robot shopping, certified compatibility or real hardware claim.'],
    ['배포 준비', '데이터·모델·장치를 확인하고 적용 흐름을 시험합니다.', 'deployment', 'Three linked cards 데이터셋 / 평가 방식 / 모의 장치. Below preflight checklist 데이터 이용, 입력 형식, 담당 FDE, 중단 방법. Right concise execution summary. Button 모의 실행. No HMAC, TensorRT, GPU or performance metrics. Clear 브라우저 UI 상태 시연.'],
    ['적용 상태 확인', '실제 장치와 구분한 브라우저 모의 기록입니다.', 'monitor', 'Clean status card 모의 실행 / 정지, three linked identifiers dataset/model/device, event list with empty state, button 모의 실행 and 모의 중단. No live factory imagery, live charts or robot controls.'],
    ['이벤트·재수집', '원래 기록을 유지하고 보완할 데이터를 연결합니다.', 'incident', 'Issue card 예시: 반사로 부품 식별 어려움. Linked source RH-MF-001, reason textarea, three checks 촬영 각도 / 조명 조건 / 라벨 기준. Button 재수집 요청 작성. Previous record preserved.'],
    ['나의 작업함', '확인할 조건과 배정된 수집 업무를 확인하세요.', 'inbox', 'Mobile big single RH-MF-001 job card with metal part thumbnail. Role 데이터 수집 오퍼레이터. Five readiness conditions and button 조건 확인 후 수집. Secondary 교육 보기 and 작업 이력. No fake pay.'],
    ['나의 현장 경력', '교육과 수행 이력으로 다음 직무를 준비합니다.', 'career', 'Mobile friendly readable portfolio. Current 데이터 수집, education 현장 안전 기초 / RGB 촬영·기록, task RH-MF-001, optional separate skills 품질 관리 / 현장 기술지원 / FDE. Explicit 별도 역량·채용 요건 필요. No levels, certificates, automatic promotion, 80-hour rules.'],
    ['데이터 접근·이용 승인', '수집 허용과 데이터 이용 승인은 별도입니다.', 'access', 'Three distinct status cards 검수 / 평가 목적 이용 / 지급. Table 조회·평가 별도 승인, 학습 미승인, 외부 공유 미승인. Buttons 평가 목적 신청 / 운영팀 모의 승인 / 승인 기록 내보내기. No actual media download.'],
    ['작업 공간 설정', '역할과 데이터 보관 원칙을 확인합니다.', 'settings', 'Simple settings tabs 역할 / 데이터 / 데모. Workspace name 제조업 중심 v1, role selector, local storage explanation and reset with confirmation. No SSO or security certification.'],
    ['데이터를 만날 현장을 찾아보세요', '공개된 조건을 확인하고 필요한 수집을 요청하세요.', 'explorer', 'Wide map-left list-right 5:7 layout. Schematic regional map labelled 예시 지도·실제 위치 아님, blue pin selected. Filters 지역 / 공정 / 데이터 / 협의 상태. Selected 한빛 정밀 모의 현장 card with metal part thumbnail, RGB 이미지, 비가동 작업대, 촬영 범위 협의 필요. Detail button and 수집 요청. National discovery, no precise GPS or claimed operational sites.'],
  ],
  'small-business': [
    ['우리 동네의 일, AI의 배움으로', '청년의 유급 데이터 수집과 소상공인 현장을 연결합니다.', 'home', 'Public hero with first-person hands arranging empty nonbreakable cups onto tray. Roles 요청 기업 / 소상공인 / 청년 현장 전문인력 / 운영팀. Flow 교육→유급 수집→검수→수행 이력. Buttons 데모 시작 and 현장 둘러보기. No POS, robot shopping, voice control or employment guarantees.'],
    ['어떤 역할로 둘러볼까요?', '요청·현장 제공·수집·검수 역할을 구분합니다.', 'entry', 'Five role cards 운영팀 / 현장 제공자 / 요청 기업 / 청년 현장 전문인력 / 검수 담당. Selected role start button. This is a UI demo, no credentials or actual login.'],
    ['오늘의 데이터 수집 운영', '교육부터 유급 수집·검수·보상 기록까지', 'overview', 'Selected scenario dashboard for either RH-SB-001 restaurant tableware sorting or RH-SB-002 neighborhood mart FIFO stocking. Six-step 요청 / 조건 합의 / 교육·배정 / 수집 / 검수 / 데이터 제공, generated scene image, next actions and three stakeholder cards. Payment separate.'],
    ['우리 동네 수집 현장', '허용된 공간과 업무를 확인하고 수집을 요청하세요.', 'explorer', 'Map:left 5, list:right7. Two clickable demo cards: restaurant table cleanup and mart refrigerated product FIFO stocking. Each has a generated image, collection conditions and explicit demo action. A third expansion card links to image-only dataset examples and says 데모 미구현.'],
    ['현장 상세·수집 조건', '촬영 구역과 허용 업무를 먼저 확인하세요.', 'site', 'Scenario-aware site detail for restaurant or mart. Generated active-scenario image, permitted work, mock environment, non-business-hours capture and operations-team supervision. Allowed/prohibited columns and collection request action. No real address.'],
    ['수집 과제', '업무·교육·보상 조건이 명확한 과제를 확인합니다.', 'tasks', 'Searchable two-row table for RH-SB-001 restaurant tableware sorting and RH-SB-002 mart FIFO stocking. Both rows are clickable demos with scenario-isolated browser records.'],
    ['새 데이터 요청', '사용할 목적과 수집·검수 기준을 먼저 정합니다.', 'request', 'Scenario-aware 3-step form: 요청 목적 / 현장 작업 영상 조건 / 교육·보상 조건. Active scenario supplies task name, purpose, site, generated image and capture conditions. Primary 요청 등록. No RFM fine tuning defaults.'],
    ['대표 현장 데이터 수집 과제', '수집할 작업과 유급 업무 조건을 확인하세요.', 'detail', 'Scenario-aware task detail for restaurant tableware sorting or mart FIFO stocking. Show active case ID, site, generated scene, scope, preparation/collection/rework conditions, supervision, allowed and excluded activities.'],
    ['교육·현장 인력 배정', '교육 확인 후 안전한 유급 수집 업무를 배정합니다.', 'assignment', 'Two-column team and five prerequisites. Youth collector A and independent reviewer B. Education, location permission, supervisor, time scope, pay/rework checked separately. Button 배정 확인. No certifications or automatic employment.'],
    ['수집을 시작하기 전에', '짧은 교육과 과제 적격 여부를 확인하세요.', 'training', 'Mobile 3 easy lesson cards: active-scenario safety / first-person capture and segment marking / compensation and rework conditions. Task guide is example, not accredited training.'],
    ['나의 작업함', '오늘 할 일과 보완 요청을 한눈에 확인하세요.', 'inbox', 'Mobile active-scenario task card with correct case ID, generated image and mock site. Role 청년 데이터 수집 오퍼레이터, 0/5 prepared conditions, primary 작업 전 확인.'],
    ['작업 전 확인', '다섯 가지 조건을 확인하면 수집을 시작할 수 있어요.', 'preflight', 'Mobile large 5-condition checklist: 교육·과제 적격 / 현장 촬영 허용 / 안전·감독 / 수행 범위·시간 / 보상·보완 조건. 0/5 progress, all unchecked. Disabled 수집 시작, explanatory reason. Compact case header, no long legal text or fixed hourly rate.'],
    ['작업 영상 수집', '허용된 영상과 작업 구간을 기록하세요.', 'capture', 'Mobile active-scenario capture flow for restaurant tableware sorting or mart FIFO stocking. Generated image labelled as an example; optional local-only video preview; task-specific segment name, timestamps, success/failure/hold and notes. No upload, live recording or robot control.'],
    ['보완·중단 내용 확인', '이유를 확인하고 다음 작업 조건을 다시 합의하세요.', 'rework', 'Mobile reason card 예시: 컵이 가려진 구간, original session link, rework condition note 준비·보완 시간도 조건 확인. Textarea 상황 기록 and local save. Buttons 조건 다시 확인 and 작업함. No forced unpaid rework.'],
    ['영상 검수', '작업 구간과 개인정보 노출 여부를 확인합니다.', 'review', 'Desktop 3-panel active-scenario review with generated scene, task-specific three-step timeline, saved segment metadata and four checks: hands/objects, segment label, personal information and capture conditions. No AI score.'],
    ['데이터셋 라이브러리', '검수된 세션을 출처·이용 조건과 함께 관리합니다.', 'library', 'Two clickable demo datasets for restaurant and mart, followed by five generated-image-only expansion examples: traditional market transport, laundry sorting, lodging bed-making, senior merchant onboarding and artisan sewing. Every expansion card says 데모 미구현.'],
    ['데이터셋 상세·버전', '영상·작업 구간과 승인된 이용 범위를 확인합니다.', 'dataset', 'Scenario-aware dataset detail for RH-DS-SB-001 or RH-DS-SB-002, with request/site/collector/reviewer provenance, saved segment records, review/access/payment status and an explicit no-RFM/no-robot boundary.'],
    ['수행·보상 이력', '준비·수집·보완 시간과 지급 확인을 구분합니다.', 'compensation', 'Four example cards 준비15분 / 수집60분 / 보완15분 / 합계90분. Active scenario case ID, title and site are shown with review and payment status. No invented guaranteed amounts or actual payout.'],
    ['데이터 접근·이용 승인', '검수 승인과 이용 승인, 지급 상태는 각각 다릅니다.', 'access', 'Separate review/access/payment status cards, purposes 조회·평가 신청 / 학습 별도 합의 / 외부 공유 불가. Buttons 평가 목적 이용 신청, 운영팀 모의 승인, 승인 기록 JSON. No blanket permission.'],
    ['작업 공간 설정', '역할과 모의 기록의 관리 범위를 확인합니다.', 'settings', 'Workspace 소상공인 중심 v1, role selector, privacy reminder no real PII, browser-only demo storage, confirm-before-reset. Simple white sections no fake security compliance.'],
  ],
};

export function specFor(sector, number) {
  const [title, subtitle, kind, brief] = specifications[sector][number - 1];
  return { title, subtitle, kind, brief };
}

export function imagePrompt(sector, number) {
  const s = specFor(sector, number);
  const mf = sector === 'manufacturing';
  const mobile = (mf ? [8,17,18] : [10,11,12,13,14]).includes(number);
  return `Use case: ui-mockup. One high-fidelity implementable Korean ${mobile ? 'mobile app screen, portrait 864x1536, no phone frame, single column, 48px touch controls' : 'desktop web app screen, landscape 1536x1024, 240px white sidebar and 64px header'}. RoboHood ${mf ? '제조업 중심' : '소상공인 중심'} v1 refined. Combine simple friendly workflow storytelling with a clean professional blue operations dashboard. Palette EXACT: #F4F7FB canvas, #FFFFFF cards, #2563EB primary, #0F172A text, #475569 secondary, #D5DDE7 border. Green only for success. No green branding, gradients, big shadows or dense tiny text. Body17px, secondary15px, headings32 desktop24 mobile relative to native viewport; readable Korean sans serif. 12px cards, 24px gaps. A small blue robot-outline RoboHood mark. One compact 'v1 · 모의 데모' badge. ${mobile ? 'Simple top back/header and four bottom items 작업함 / 수집 / 교육 / 이력. No desktop sidebar.' : `Sidebar labels ${mf ? '개요 / 현장 탐색 / 현장 과제 / 현장 인력 / 검수·라벨링 / 데이터셋 / 모델 / 장비 / 배포·관제 / 접근 승인 / 설정' : '개요 / 현장 탐색 / 수집 과제 / 교육·현장 인력 / 검수 / 데이터셋 / 수행·보상 / 접근 승인 / 설정'}. Select the current page. Header role button and 전체 화면 link. No duplicate toolbars.`} Page heading verbatim '${s.title}'. Subtitle verbatim '${s.subtitle}'. Content: ${s.brief} ${mf ? 'Canonical case RH-MF-001, 소형 부품 외관 검사, 한빛 정밀 mock safe table, RGB collection only. Youth collector and FDE are separate roles.' : 'Two clickable canonical demos: RH-SB-001 restaurant tableware sorting and RH-SB-002 neighborhood mart refrigerated-product FIFO stocking. Other scenarios are generated-image-only dataset examples marked demo not implemented. No live model, sensor telemetry or robot control. Photos show consenting adults without identifiable faces, customers, logos or real business data.'} State all illustrative data as '예시' or '모의'. Do not invent performance metrics, legal guarantees, certifications, partnerships, salaries, live AI, payment or employment claims. Clear hierarchy, one main action. No multi-screen collage. This image is a design reference for subsequent actual HTML/CSS implementation; no code printed in image.`;
}
